// session_enricher.go — Enriches sessions with journal data on completion.
// Author: Subash Karki
package collector

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log/slog"
	"regexp"
	"strings"
	"time"

	"github.com/subashkarki/phantom-os-v2/internal/db"
)

// SessionEnricher aggregates activity data into journal fields when a session ends.
type SessionEnricher struct {
	queries   *db.Queries
	rawDB     db.DBTX
	emitEvent func(name string, data interface{})
}

// NewSessionEnricher creates a SessionEnricher.
// rawDB is needed for queries not yet generated by sqlc (journal column updates, daily_stats upserts).
func NewSessionEnricher(queries *db.Queries, rawDB db.DBTX, emitEvent func(string, interface{})) *SessionEnricher {
	return &SessionEnricher{queries: queries, rawDB: rawDB, emitEvent: emitEvent}
}

// EnrichSession runs after a session ends — aggregates activity data into journal fields.
func (se *SessionEnricher) EnrichSession(ctx context.Context, sessionID string) {
	session, err := se.queries.GetSession(ctx, sessionID)
	if err != nil {
		slog.Error("session_enricher: get session", "session_id", sessionID, "err", err)
		return
	}

	// 1. Compute date from started_at.
	date := time.Unix(session.StartedAt.Int64, 0).Format("2006-01-02")

	// 2. Aggregate files touched from activity_log.
	filesTouched := se.aggregateFiles(ctx, sessionID)

	// 3. Count git commits and line stats from activity_log.
	gitCommits, linesAdded, linesRemoved := se.aggregateGitStats(ctx, sessionID)

	// 4. Generate heuristic summary.
	summary := se.generateSummary(session, filesTouched, gitCommits)

	// 5. Determine outcome.
	outcome := se.determineOutcome(session)

	// 6. Detect branch from activity events.
	branch := se.detectBranch(ctx, sessionID)

	// 7. Look up PR from activity events.
	prURL, prStatus := se.lookupPR(ctx, sessionID)

	// 8. Persist journal data via raw SQL (journal columns from migration 003).
	filesTouchedJSON, _ := json.Marshal(filesTouched)
	_, err = se.rawDB.ExecContext(ctx,
		`UPDATE sessions SET date=?, summary=?, outcome=?, files_touched=?, git_commits=?, git_lines_added=?, git_lines_removed=?, branch=?, pr_url=?, pr_status=? WHERE id=?`,
		date, summary, outcome, string(filesTouchedJSON), gitCommits, linesAdded, linesRemoved, branch, prURL, prStatus, sessionID)
	if err != nil {
		slog.Error("session_enricher: update journal", "session_id", sessionID, "err", err)
		return
	}

	// 9. Upsert daily stats.
	se.upsertDailyStats(ctx, date, session)

	// 10. Emit event for frontend.
	if se.emitEvent != nil {
		se.emitEvent(EventJournalEnriched, map[string]interface{}{
			"sessionId": sessionID,
			"date":      date,
		})
	}

	slog.Info("session_enricher: enriched", "session_id", sessionID, "files", len(filesTouched), "commits", gitCommits)
}

// aggregateFiles extracts unique file paths from tool activity events.
func (se *SessionEnricher) aggregateFiles(ctx context.Context, sessionID string) []string {
	activities, err := se.queries.ListRecentActivity(ctx, db.ListRecentActivityParams{
		SessionID: sql.NullString{String: sessionID, Valid: true},
		Column2:   sessionID,
		Limit:     5000,
	})
	if err != nil {
		slog.Error("session_enricher: list activity for files", "session_id", sessionID, "err", err)
		return nil
	}

	seen := make(map[string]struct{})
	var files []string

	for _, a := range activities {
		// Only tool events carry file paths.
		if !strings.HasPrefix(a.Type, "tool:") {
			continue
		}
		if !a.Metadata.Valid {
			continue
		}

		var meta map[string]string
		if err := json.Unmarshal([]byte(a.Metadata.String), &meta); err != nil {
			continue
		}

		detail := meta["detail"]
		if detail == "" {
			continue
		}

		// Read, Edit, Write tools store file paths in detail.
		toolType := a.Type
		if toolType == "tool:read" || toolType == "tool:edit" || toolType == "tool:write" {
			path := strings.TrimSpace(detail)
			if path != "" && !strings.Contains(path, " ") {
				if _, ok := seen[path]; !ok {
					seen[path] = struct{}{}
					files = append(files, path)
				}
			}
		}
	}

	return files
}

// gitStatRegex matches common git diff stat patterns like "+5/-3" or "5 insertions(+), 3 deletions(-)".
var gitStatRegex = regexp.MustCompile(`(\d+)\s+insertions?\(\+\).*?(\d+)\s+deletions?\(-\)`)

// gitShortStatRegex matches compact "+N/-N" patterns.
var gitShortStatRegex = regexp.MustCompile(`\+(\d+)/-(\d+)`)

// aggregateGitStats counts commits and line changes from git activity events.
func (se *SessionEnricher) aggregateGitStats(ctx context.Context, sessionID string) (commits, added, removed int64) {
	activities, err := se.queries.ListRecentActivity(ctx, db.ListRecentActivityParams{
		SessionID: sql.NullString{String: sessionID, Valid: true},
		Column2:   sessionID,
		Limit:     5000,
	})
	if err != nil {
		slog.Error("session_enricher: list activity for git stats", "session_id", sessionID, "err", err)
		return 0, 0, 0
	}

	for _, a := range activities {
		if !strings.HasPrefix(a.Type, "git:") {
			continue
		}

		if a.Type == "git:commit" {
			commits++
		}

		if !a.Metadata.Valid {
			continue
		}

		var meta map[string]string
		if err := json.Unmarshal([]byte(a.Metadata.String), &meta); err != nil {
			continue
		}

		detail := meta["detail"]
		if detail == "" {
			continue
		}

		// Try verbose pattern: "5 insertions(+), 3 deletions(-)"
		if m := gitStatRegex.FindStringSubmatch(detail); len(m) == 3 {
			var a, r int64
			fmt.Sscanf(m[1], "%d", &a)
			fmt.Sscanf(m[2], "%d", &r)
			added += a
			removed += r
			continue
		}

		// Try short pattern: "+5/-3"
		if m := gitShortStatRegex.FindStringSubmatch(detail); len(m) == 3 {
			var a, r int64
			fmt.Sscanf(m[1], "%d", &a)
			fmt.Sscanf(m[2], "%d", &r)
			added += a
			removed += r
		}
	}

	return commits, added, removed
}

// generateSummary creates a heuristic summary from session data.
func (se *SessionEnricher) generateSummary(session db.Session, files []string, commits int64) string {
	base := ""
	if session.FirstPrompt.Valid && session.FirstPrompt.String != "" {
		base = session.FirstPrompt.String
		if len(base) > 100 {
			base = base[:100] + "..."
		}
	} else if session.Repo.Valid && session.Repo.String != "" {
		base = fmt.Sprintf("Session in %s", session.Repo.String)
	} else {
		base = "Coding session"
	}

	var parts []string
	if len(files) > 0 {
		parts = append(parts, fmt.Sprintf("%d files edited", len(files)))
	}
	if commits > 0 {
		parts = append(parts, fmt.Sprintf("%d commits", commits))
	}

	if len(parts) > 0 {
		return fmt.Sprintf("%s — %s", base, strings.Join(parts, ", "))
	}
	return base
}

// determineOutcome classifies the session result.
func (se *SessionEnricher) determineOutcome(session db.Session) string {
	if session.Status.Valid && session.Status.String == "completed" {
		// If very few messages, likely abandoned.
		if session.MessageCount.Valid && session.MessageCount.Int64 <= 1 {
			return "abandoned"
		}
		return "completed"
	}
	return "completed"
}

// detectBranch finds the git branch from activity events.
func (se *SessionEnricher) detectBranch(ctx context.Context, sessionID string) string {
	activities, err := se.queries.ListRecentActivity(ctx, db.ListRecentActivityParams{
		SessionID: sql.NullString{String: sessionID, Valid: true},
		Column2:   sessionID,
		Limit:     5000,
	})
	if err != nil {
		return ""
	}

	// Walk backwards (most recent first) looking for git:checkout or git:branch events.
	for _, a := range activities {
		if a.Type != "git:checkout" && a.Type != "git:branch" {
			continue
		}
		if !a.Metadata.Valid {
			continue
		}

		var meta map[string]string
		if err := json.Unmarshal([]byte(a.Metadata.String), &meta); err != nil {
			continue
		}

		detail := meta["detail"]
		if detail == "" {
			continue
		}

		// Extract branch name from checkout/branch commands.
		// "git checkout feature/foo" or "git checkout -b feature/foo"
		branch := extractBranchFromCommand(detail)
		if branch != "" {
			return branch
		}
	}

	return ""
}

// branchCmdRegex matches "git checkout [-b] <branch>" or "git branch <branch>".
var branchCmdRegex = regexp.MustCompile(`git\s+(?:checkout(?:\s+-[bB])?\s+|branch\s+)(\S+)`)

// extractBranchFromCommand parses a branch name from a git command string.
func extractBranchFromCommand(cmd string) string {
	m := branchCmdRegex.FindStringSubmatch(cmd)
	if len(m) < 2 {
		return ""
	}
	branch := m[1]
	// Filter out flags.
	if strings.HasPrefix(branch, "-") {
		return ""
	}
	return branch
}

// lookupPR searches activity events for PR URLs from git:push events.
func (se *SessionEnricher) lookupPR(ctx context.Context, sessionID string) (prURL, prStatus string) {
	activities, err := se.queries.ListRecentActivity(ctx, db.ListRecentActivityParams{
		SessionID: sql.NullString{String: sessionID, Valid: true},
		Column2:   sessionID,
		Limit:     5000,
	})
	if err != nil {
		return "", ""
	}

	// Check push events for PR URLs in the output.
	prURLRegex := regexp.MustCompile(`https://github\.com/[^\s]+/pull/\d+`)

	for _, a := range activities {
		if a.Type != "git:push" {
			continue
		}
		if !a.Metadata.Valid {
			continue
		}

		var meta map[string]string
		if err := json.Unmarshal([]byte(a.Metadata.String), &meta); err != nil {
			continue
		}

		detail := meta["detail"]
		if m := prURLRegex.FindString(detail); m != "" {
			return m, "open"
		}
	}

	return "", ""
}

// upsertDailyStats aggregates all sessions for a given date and upserts into daily_stats.
func (se *SessionEnricher) upsertDailyStats(ctx context.Context, date string, session db.Session) {
	// Query all sessions for this date to compute aggregates.
	rows, err := se.rawDB.QueryContext(ctx,
		`SELECT
			COUNT(*) as session_count,
			COALESCE(SUM(CASE WHEN ended_at IS NOT NULL AND started_at IS NOT NULL THEN ended_at - started_at ELSE 0 END), 0) as total_duration,
			COALESCE(SUM(estimated_cost_micros), 0) as total_cost,
			COALESCE(SUM(input_tokens), 0) as total_input,
			COALESCE(SUM(output_tokens), 0) as total_output,
			COALESCE(SUM(tool_use_count), 0) as total_tools,
			COALESCE(SUM(git_commits), 0) as total_commits
		FROM sessions WHERE date = ?`, date)
	if err != nil {
		slog.Error("session_enricher: query daily stats", "date", date, "err", err)
		return
	}
	defer rows.Close()

	var sessionCount, totalDuration, totalCost, totalInput, totalOutput, totalTools, totalCommits int64
	if rows.Next() {
		if err := rows.Scan(&sessionCount, &totalDuration, &totalCost, &totalInput, &totalOutput, &totalTools, &totalCommits); err != nil {
			slog.Error("session_enricher: scan daily stats", "date", date, "err", err)
			return
		}
	}
	rows.Close()

	// Determine project_id from session repo (default to '__global__').
	projectID := "__global__"
	if session.Repo.Valid && session.Repo.String != "" {
		projectID = session.Repo.String
	}

	// Upsert into daily_stats.
	_, err = se.rawDB.ExecContext(ctx,
		`INSERT INTO daily_stats (date, project_id, session_count, total_duration_secs, total_cost_micros, total_input_tokens, total_output_tokens, total_tool_calls, total_commits)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT (date, project_id) DO UPDATE SET
			session_count = excluded.session_count,
			total_duration_secs = excluded.total_duration_secs,
			total_cost_micros = excluded.total_cost_micros,
			total_input_tokens = excluded.total_input_tokens,
			total_output_tokens = excluded.total_output_tokens,
			total_tool_calls = excluded.total_tool_calls,
			total_commits = excluded.total_commits`,
		date, projectID, sessionCount, totalDuration, totalCost, totalInput, totalOutput, totalTools, totalCommits)
	if err != nil {
		slog.Error("session_enricher: upsert daily stats", "date", date, "err", err)
	}
}
