// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"
	"database/sql"
)

const insertActivity = `-- name: InsertActivity :exec

INSERT INTO activity_log (
    timestamp, type, session_id, metadata, xp_earned, provider
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type InsertActivityParams struct {
	Timestamp int64          `json:"timestamp"`
	Type      string         `json:"type"`
	SessionID sql.NullString `json:"session_id"`
	Metadata  sql.NullString `json:"metadata"`
	XpEarned  sql.NullInt64  `json:"xp_earned"`
	Provider  string         `json:"provider"`
}

// activity.sql - Operations for activity_log table
// Author: Subash Karki
func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, insertActivity,
		arg.Timestamp,
		arg.Type,
		arg.SessionID,
		arg.Metadata,
		arg.XpEarned,
		arg.Provider,
	)
	return err
}

const listActivityByProvider = `-- name: ListActivityByProvider :many
SELECT id, timestamp, type, session_id, metadata, xp_earned, provider FROM activity_log
WHERE provider = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListActivityByProviderParams struct {
	Provider string `json:"provider"`
	Limit    int64  `json:"limit"`
}

func (q *Queries) ListActivityByProvider(ctx context.Context, arg ListActivityByProviderParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listActivityByProvider, arg.Provider, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Type,
			&i.SessionID,
			&i.Metadata,
			&i.XpEarned,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT id, timestamp, type, session_id, metadata, xp_earned, provider FROM activity_log
WHERE (session_id = ? OR ? IS NULL)
ORDER BY timestamp DESC
LIMIT ?
`

type ListRecentActivityParams struct {
	SessionID sql.NullString `json:"session_id"`
	Column2   interface{}    `json:"column_2"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]ActivityLog, error) {
	rows, err := q.db.QueryContext(ctx, listRecentActivity, arg.SessionID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Type,
			&i.SessionID,
			&i.Metadata,
			&i.XpEarned,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
