// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"database/sql"
)

const createConversation = `-- name: CreateConversation :exec
INSERT INTO chat_conversations (id, workspace_id, title, model, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID          string         `json:"id"`
	WorkspaceID sql.NullString `json:"workspace_id"`
	Title       string         `json:"title"`
	Model       sql.NullString `json:"model"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Model,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO chat_messages (id, conversation_id, workspace_id, role, content, model, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID             string         `json:"id"`
	ConversationID sql.NullString `json:"conversation_id"`
	WorkspaceID    sql.NullString `json:"workspace_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Model          sql.NullString `json:"model"`
	CreatedAt      int64          `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.WorkspaceID,
		arg.Role,
		arg.Content,
		arg.Model,
		arg.CreatedAt,
	)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM chat_conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :exec
DELETE FROM chat_messages WHERE conversation_id = ?
`

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, conversationID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesByConversation, conversationID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, workspace_id, title, model, created_at, updated_at FROM chat_conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (ChatConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i ChatConversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByWorkspace = `-- name: ListConversationsByWorkspace :many

SELECT id, workspace_id, title, model, created_at, updated_at FROM chat_conversations
WHERE workspace_id = ?
ORDER BY updated_at DESC
`

// chat.sql - CRUD operations for chat_conversations and chat_messages tables
// Author: Subash Karki
func (q *Queries) ListConversationsByWorkspace(ctx context.Context, workspaceID sql.NullString) ([]ChatConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatConversation{}
	for rows.Next() {
		var i ChatConversation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, workspace_id, role, content, model, created_at FROM chat_messages
WHERE conversation_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID sql.NullString) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.WorkspaceID,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationTimestamp = `-- name: UpdateConversationTimestamp :exec
UPDATE chat_conversations SET updated_at = ? WHERE id = ?
`

type UpdateConversationTimestampParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateConversationTimestamp(ctx context.Context, arg UpdateConversationTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationTimestamp, arg.UpdatedAt, arg.ID)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE chat_conversations SET title = ?, updated_at = ? WHERE id = ?
`

type UpdateConversationTitleParams struct {
	Title     string `json:"title"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}
