// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fts_search.sql

package db

import (
	"context"
	"database/sql"
)

const insertMemory = `-- name: InsertMemory :exec
INSERT INTO session_memories_fts(memory_text, memory_type, session_id)
VALUES (?1, ?2, ?3)
`

type InsertMemoryParams struct {
	MemoryText string `json:"memory_text"`
	MemoryType string `json:"memory_type"`
	SessionID  string `json:"session_id"`
}

// Insert a session memory into the standalone FTS5 index.
func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMemory, arg.MemoryText, arg.MemoryType, arg.SessionID)
	return err
}

const insertPattern = `-- name: InsertPattern :exec
INSERT INTO ai_patterns_fts(pattern_text, category, source_context)
VALUES (?1, ?2, ?3)
`

type InsertPatternParams struct {
	PatternText   string `json:"pattern_text"`
	Category      string `json:"category"`
	SourceContext string `json:"source_context"`
}

// Insert a knowledge pattern into the standalone FTS5 index.
func (q *Queries) InsertPattern(ctx context.Context, arg InsertPatternParams) error {
	_, err := q.db.ExecContext(ctx, insertPattern, arg.PatternText, arg.Category, arg.SourceContext)
	return err
}

const searchDecisions = `-- name: SearchDecisions :many

SELECT
    d.id,
    d.goal,
    d.strategy_id,
    d.complexity,
    d.risk,
    d.confidence,
    d.created_at
FROM ai_decisions d
JOIN ai_decisions_fts ON d.rowid = ai_decisions_fts.rowid
WHERE ai_decisions_fts.goal MATCH ?1
ORDER BY ai_decisions_fts.rank
`

type SearchDecisionsRow struct {
	ID         string          `json:"id"`
	Goal       string          `json:"goal"`
	StrategyID string          `json:"strategy_id"`
	Complexity sql.NullString  `json:"complexity"`
	Risk       sql.NullString  `json:"risk"`
	Confidence sql.NullFloat64 `json:"confidence"`
	CreatedAt  sql.NullTime    `json:"created_at"`
}

// fts_search.sql
// FTS5 full-text search queries for AI decision matching,
// pattern retrieval, and session memory search.
// Author: Subash Karki
// Full-text search over AI decisions ordered by FTS5 relevance rank.
// Pass a FTS5 match expression, e.g. "deploy strategy" or "goal:migrate*".
func (q *Queries) SearchDecisions(ctx context.Context, query string) ([]SearchDecisionsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDecisions, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDecisionsRow{}
	for rows.Next() {
		var i SearchDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Goal,
			&i.StrategyID,
			&i.Complexity,
			&i.Risk,
			&i.Confidence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT
    memory_text,
    memory_type,
    session_id
FROM session_memories_fts
WHERE memory_text MATCH ?1
ORDER BY rank
`

// Full-text search over session memories ordered by FTS5 relevance rank.
func (q *Queries) SearchMemories(ctx context.Context, query string) ([]SessionMemoriesFt, error) {
	rows, err := q.db.QueryContext(ctx, searchMemories, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionMemoriesFt{}
	for rows.Next() {
		var i SessionMemoriesFt
		if err := rows.Scan(&i.MemoryText, &i.MemoryType, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatterns = `-- name: SearchPatterns :many
SELECT
    pattern_text,
    category,
    source_context
FROM ai_patterns_fts
WHERE pattern_text MATCH ?1
ORDER BY rank
`

// Full-text search over knowledge patterns ordered by FTS5 relevance rank.
func (q *Queries) SearchPatterns(ctx context.Context, query string) ([]AiPatternsFt, error) {
	rows, err := q.db.QueryContext(ctx, searchPatterns, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiPatternsFt{}
	for rows.Next() {
		var i AiPatternsFt
		if err := rows.Scan(&i.PatternText, &i.Category, &i.SourceContext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
