// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gamification.sql

package db

import (
	"context"
	"database/sql"
)

const createDailyQuest = `-- name: CreateDailyQuest :exec
INSERT INTO daily_quests (id, date, quest_type, label, target, progress, completed, xp_reward)
VALUES (?, ?, ?, ?, ?, 0, 0, ?)
`

type CreateDailyQuestParams struct {
	ID        string        `json:"id"`
	Date      string        `json:"date"`
	QuestType string        `json:"quest_type"`
	Label     string        `json:"label"`
	Target    int64         `json:"target"`
	XpReward  sql.NullInt64 `json:"xp_reward"`
}

func (q *Queries) CreateDailyQuest(ctx context.Context, arg CreateDailyQuestParams) error {
	_, err := q.db.ExecContext(ctx, createDailyQuest,
		arg.ID,
		arg.Date,
		arg.QuestType,
		arg.Label,
		arg.Target,
		arg.XpReward,
	)
	return err
}

const ensureHunterProfile = `-- name: EnsureHunterProfile :exec
INSERT OR IGNORE INTO hunter_profile (id, name, level, xp, xp_to_next, rank, title, total_sessions, total_tasks, total_repos, streak_current, streak_best, created_at)
VALUES (1, 'Hunter', 1, 0, 100, 'F', 'Awakened', 0, 0, 0, 0, 0, unixepoch() * 1000)
`

func (q *Queries) EnsureHunterProfile(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureHunterProfile)
	return err
}

const ensureHunterStats = `-- name: EnsureHunterStats :exec
INSERT OR IGNORE INTO hunter_stats (id, strength, intelligence, agility, vitality, perception, sense)
VALUES (1, 10, 10, 10, 10, 10, 10)
`

func (q *Queries) EnsureHunterStats(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureHunterStats)
	return err
}

const getAchievement = `-- name: GetAchievement :one
SELECT id, name, description, icon, category, xp_reward, unlocked_at FROM achievements WHERE id = ?
`

func (q *Queries) GetAchievement(ctx context.Context, id string) (Achievement, error) {
	row := q.db.QueryRowContext(ctx, getAchievement, id)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Category,
		&i.XpReward,
		&i.UnlockedAt,
	)
	return i, err
}

const getCompletedTaskCountForDate = `-- name: GetCompletedTaskCountForDate :one
SELECT COUNT(*) as cnt FROM tasks
WHERE status = 'completed' AND updated_at >= ? AND updated_at < ?
`

type GetCompletedTaskCountForDateParams struct {
	UpdatedAt   sql.NullInt64 `json:"updated_at"`
	UpdatedAt_2 sql.NullInt64 `json:"updated_at_2"`
}

func (q *Queries) GetCompletedTaskCountForDate(ctx context.Context, arg GetCompletedTaskCountForDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCompletedTaskCountForDate, arg.UpdatedAt, arg.UpdatedAt_2)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getDailyActivity = `-- name: GetDailyActivity :many
SELECT
    date,
    COALESCE(session_count, 0) as session_count,
    COALESCE(total_duration_secs, 0) as total_duration_secs,
    COALESCE(total_cost_micros, 0) as total_cost_micros
FROM daily_stats
ORDER BY date DESC
LIMIT ?
`

type GetDailyActivityRow struct {
	Date              string `json:"date"`
	SessionCount      int64  `json:"session_count"`
	TotalDurationSecs int64  `json:"total_duration_secs"`
	TotalCostMicros   int64  `json:"total_cost_micros"`
}

func (q *Queries) GetDailyActivity(ctx context.Context, limit int64) ([]GetDailyActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyActivityRow{}
	for rows.Next() {
		var i GetDailyActivityRow
		if err := rows.Scan(
			&i.Date,
			&i.SessionCount,
			&i.TotalDurationSecs,
			&i.TotalCostMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHunterProfile = `-- name: GetHunterProfile :one

SELECT id, name, level, xp, xp_to_next, rank, title, total_sessions, total_tasks, total_repos, streak_current, streak_best, last_active_date, created_at FROM hunter_profile WHERE id = 1
`

// gamification.sql - Queries for hunter profile, stats, achievements, and daily quests.
// Author: Subash Karki
func (q *Queries) GetHunterProfile(ctx context.Context) (HunterProfile, error) {
	row := q.db.QueryRowContext(ctx, getHunterProfile)
	var i HunterProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Xp,
		&i.XpToNext,
		&i.Rank,
		&i.Title,
		&i.TotalSessions,
		&i.TotalTasks,
		&i.TotalRepos,
		&i.StreakCurrent,
		&i.StreakBest,
		&i.LastActiveDate,
		&i.CreatedAt,
	)
	return i, err
}

const getHunterStats = `-- name: GetHunterStats :one
SELECT id, strength, intelligence, agility, vitality, perception, sense FROM hunter_stats WHERE id = 1
`

func (q *Queries) GetHunterStats(ctx context.Context) (HunterStat, error) {
	row := q.db.QueryRowContext(ctx, getHunterStats)
	var i HunterStat
	err := row.Scan(
		&i.ID,
		&i.Strength,
		&i.Intelligence,
		&i.Agility,
		&i.Vitality,
		&i.Perception,
		&i.Sense,
	)
	return i, err
}

const getLifetimeStats = `-- name: GetLifetimeStats :one
SELECT
    COUNT(*) as total_sessions,
    COALESCE(SUM(input_tokens + output_tokens), 0) as total_tokens,
    COALESCE(SUM(estimated_cost_micros), 0) as total_cost
FROM sessions
`

type GetLifetimeStatsRow struct {
	TotalSessions int64       `json:"total_sessions"`
	TotalTokens   interface{} `json:"total_tokens"`
	TotalCost     interface{} `json:"total_cost"`
}

func (q *Queries) GetLifetimeStats(ctx context.Context) (GetLifetimeStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getLifetimeStats)
	var i GetLifetimeStatsRow
	err := row.Scan(&i.TotalSessions, &i.TotalTokens, &i.TotalCost)
	return i, err
}

const getLongSessionCountForDate = `-- name: GetLongSessionCountForDate :one
SELECT COUNT(*) as cnt FROM sessions
WHERE started_at >= ? AND started_at < ?
  AND ended_at IS NOT NULL
  AND (ended_at - started_at) > 3600000
`

type GetLongSessionCountForDateParams struct {
	StartedAt   sql.NullInt64 `json:"started_at"`
	StartedAt_2 sql.NullInt64 `json:"started_at_2"`
}

func (q *Queries) GetLongSessionCountForDate(ctx context.Context, arg GetLongSessionCountForDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLongSessionCountForDate, arg.StartedAt, arg.StartedAt_2)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getModelBreakdown = `-- name: GetModelBreakdown :many
SELECT
    model,
    COUNT(*) as sessions,
    COALESCE(SUM(input_tokens + output_tokens), 0) as tokens,
    COALESCE(SUM(estimated_cost_micros), 0) as cost
FROM sessions
WHERE model IS NOT NULL
GROUP BY model
`

type GetModelBreakdownRow struct {
	Model    sql.NullString `json:"model"`
	Sessions int64          `json:"sessions"`
	Tokens   interface{}    `json:"tokens"`
	Cost     interface{}    `json:"cost"`
}

func (q *Queries) GetModelBreakdown(ctx context.Context) ([]GetModelBreakdownRow, error) {
	rows, err := q.db.QueryContext(ctx, getModelBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModelBreakdownRow{}
	for rows.Next() {
		var i GetModelBreakdownRow
		if err := rows.Scan(
			&i.Model,
			&i.Sessions,
			&i.Tokens,
			&i.Cost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerfectSessionCountForDate = `-- name: GetPerfectSessionCountForDate :one
SELECT COUNT(*) as cnt FROM sessions
WHERE started_at >= ? AND started_at < ?
  AND task_count > 0
  AND completed_tasks = task_count
`

type GetPerfectSessionCountForDateParams struct {
	StartedAt   sql.NullInt64 `json:"started_at"`
	StartedAt_2 sql.NullInt64 `json:"started_at_2"`
}

func (q *Queries) GetPerfectSessionCountForDate(ctx context.Context, arg GetPerfectSessionCountForDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPerfectSessionCountForDate, arg.StartedAt, arg.StartedAt_2)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getSessionCountForDate = `-- name: GetSessionCountForDate :one
SELECT COUNT(*) as cnt FROM sessions
WHERE started_at >= ? AND started_at < ?
`

type GetSessionCountForDateParams struct {
	StartedAt   sql.NullInt64 `json:"started_at"`
	StartedAt_2 sql.NullInt64 `json:"started_at_2"`
}

func (q *Queries) GetSessionCountForDate(ctx context.Context, arg GetSessionCountForDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionCountForDate, arg.StartedAt, arg.StartedAt_2)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getSpeedTaskCountForDate = `-- name: GetSpeedTaskCountForDate :one
SELECT COUNT(*) as cnt FROM tasks
WHERE status = 'completed'
  AND updated_at >= ? AND updated_at < ?
  AND (updated_at - created_at) < 120000
`

type GetSpeedTaskCountForDateParams struct {
	UpdatedAt   sql.NullInt64 `json:"updated_at"`
	UpdatedAt_2 sql.NullInt64 `json:"updated_at_2"`
}

func (q *Queries) GetSpeedTaskCountForDate(ctx context.Context, arg GetSpeedTaskCountForDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSpeedTaskCountForDate, arg.UpdatedAt, arg.UpdatedAt_2)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getTotalSpeedTasks = `-- name: GetTotalSpeedTasks :one
SELECT COUNT(*) as cnt FROM tasks
WHERE status = 'completed'
  AND (updated_at - created_at) < 120000
`

func (q *Queries) GetTotalSpeedTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSpeedTasks)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getTotalXPEarned = `-- name: GetTotalXPEarned :one
SELECT COALESCE(SUM(xp_earned), 0) as total_xp FROM activity_log
`

func (q *Queries) GetTotalXPEarned(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalXPEarned)
	var total_xp interface{}
	err := row.Scan(&total_xp)
	return total_xp, err
}

const getUniqueRepoCount = `-- name: GetUniqueRepoCount :one
SELECT COUNT(DISTINCT repo) as cnt FROM sessions WHERE repo IS NOT NULL
`

func (q *Queries) GetUniqueRepoCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUniqueRepoCount)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getUniqueRepoCountForDate = `-- name: GetUniqueRepoCountForDate :one
SELECT COUNT(DISTINCT repo) as cnt FROM sessions
WHERE started_at >= ? AND started_at < ?
  AND repo IS NOT NULL
`

type GetUniqueRepoCountForDateParams struct {
	StartedAt   sql.NullInt64 `json:"started_at"`
	StartedAt_2 sql.NullInt64 `json:"started_at_2"`
}

func (q *Queries) GetUniqueRepoCountForDate(ctx context.Context, arg GetUniqueRepoCountForDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUniqueRepoCountForDate, arg.StartedAt, arg.StartedAt_2)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const incrementStat = `-- name: IncrementStat :exec
UPDATE hunter_stats SET
    strength = CASE WHEN ?1 = 'strength' THEN COALESCE(strength, 10) + ?2 ELSE strength END,
    intelligence = CASE WHEN ?1 = 'intelligence' THEN COALESCE(intelligence, 10) + ?2 ELSE intelligence END,
    agility = CASE WHEN ?1 = 'agility' THEN COALESCE(agility, 10) + ?2 ELSE agility END,
    vitality = CASE WHEN ?1 = 'vitality' THEN COALESCE(vitality, 10) + ?2 ELSE vitality END,
    perception = CASE WHEN ?1 = 'perception' THEN COALESCE(perception, 10) + ?2 ELSE perception END,
    sense = CASE WHEN ?1 = 'sense' THEN COALESCE(sense, 10) + ?2 ELSE sense END
WHERE id = 1
`

type IncrementStatParams struct {
	Stat   interface{}   `json:"stat"`
	Amount sql.NullInt64 `json:"amount"`
}

func (q *Queries) IncrementStat(ctx context.Context, arg IncrementStatParams) error {
	_, err := q.db.ExecContext(ctx, incrementStat, arg.Stat, arg.Amount)
	return err
}

const incrementTotalRepos = `-- name: IncrementTotalRepos :exec
UPDATE hunter_profile SET total_repos = COALESCE(total_repos, 0) + 1 WHERE id = 1
`

func (q *Queries) IncrementTotalRepos(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, incrementTotalRepos)
	return err
}

const incrementTotalSessions = `-- name: IncrementTotalSessions :exec
UPDATE hunter_profile SET total_sessions = COALESCE(total_sessions, 0) + 1 WHERE id = 1
`

func (q *Queries) IncrementTotalSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, incrementTotalSessions)
	return err
}

const incrementTotalTasks = `-- name: IncrementTotalTasks :exec
UPDATE hunter_profile SET total_tasks = COALESCE(total_tasks, 0) + 1 WHERE id = 1
`

func (q *Queries) IncrementTotalTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, incrementTotalTasks)
	return err
}

const listAchievements = `-- name: ListAchievements :many
SELECT id, name, description, icon, category, xp_reward, unlocked_at FROM achievements ORDER BY category, name
`

func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.QueryContext(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Category,
			&i.XpReward,
			&i.UnlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyQuests = `-- name: ListDailyQuests :many
SELECT id, date, quest_type, label, target, progress, completed, xp_reward FROM daily_quests WHERE date = ?
`

func (q *Queries) ListDailyQuests(ctx context.Context, date string) ([]DailyQuest, error) {
	rows, err := q.db.QueryContext(ctx, listDailyQuests, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyQuest{}
	for rows.Next() {
		var i DailyQuest
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.QuestType,
			&i.Label,
			&i.Target,
			&i.Progress,
			&i.Completed,
			&i.XpReward,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logActivity = `-- name: LogActivity :exec
INSERT INTO activity_log (timestamp, type, session_id, metadata, xp_earned, provider)
VALUES (?, ?, ?, ?, ?, 'gamification')
`

type LogActivityParams struct {
	Timestamp int64          `json:"timestamp"`
	Type      string         `json:"type"`
	SessionID sql.NullString `json:"session_id"`
	Metadata  sql.NullString `json:"metadata"`
	XpEarned  sql.NullInt64  `json:"xp_earned"`
}

func (q *Queries) LogActivity(ctx context.Context, arg LogActivityParams) error {
	_, err := q.db.ExecContext(ctx, logActivity,
		arg.Timestamp,
		arg.Type,
		arg.SessionID,
		arg.Metadata,
		arg.XpEarned,
	)
	return err
}

const unlockAchievement = `-- name: UnlockAchievement :exec
UPDATE achievements SET unlocked_at = ? WHERE id = ?
`

type UnlockAchievementParams struct {
	UnlockedAt sql.NullInt64 `json:"unlocked_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UnlockAchievement(ctx context.Context, arg UnlockAchievementParams) error {
	_, err := q.db.ExecContext(ctx, unlockAchievement, arg.UnlockedAt, arg.ID)
	return err
}

const updateHunterName = `-- name: UpdateHunterName :exec
UPDATE hunter_profile SET name = ? WHERE id = 1
`

func (q *Queries) UpdateHunterName(ctx context.Context, name sql.NullString) error {
	_, err := q.db.ExecContext(ctx, updateHunterName, name)
	return err
}

const updateHunterProfile = `-- name: UpdateHunterProfile :exec
UPDATE hunter_profile SET
    name = ?,
    level = ?,
    xp = ?,
    xp_to_next = ?,
    rank = ?,
    title = ?,
    total_sessions = ?,
    total_tasks = ?,
    total_repos = ?,
    streak_current = ?,
    streak_best = ?,
    last_active_date = ?
WHERE id = 1
`

type UpdateHunterProfileParams struct {
	Name           sql.NullString `json:"name"`
	Level          sql.NullInt64  `json:"level"`
	Xp             sql.NullInt64  `json:"xp"`
	XpToNext       sql.NullInt64  `json:"xp_to_next"`
	Rank           sql.NullString `json:"rank"`
	Title          sql.NullString `json:"title"`
	TotalSessions  sql.NullInt64  `json:"total_sessions"`
	TotalTasks     sql.NullInt64  `json:"total_tasks"`
	TotalRepos     sql.NullInt64  `json:"total_repos"`
	StreakCurrent  sql.NullInt64  `json:"streak_current"`
	StreakBest     sql.NullInt64  `json:"streak_best"`
	LastActiveDate sql.NullString `json:"last_active_date"`
}

func (q *Queries) UpdateHunterProfile(ctx context.Context, arg UpdateHunterProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateHunterProfile,
		arg.Name,
		arg.Level,
		arg.Xp,
		arg.XpToNext,
		arg.Rank,
		arg.Title,
		arg.TotalSessions,
		arg.TotalTasks,
		arg.TotalRepos,
		arg.StreakCurrent,
		arg.StreakBest,
		arg.LastActiveDate,
	)
	return err
}

const updateHunterXP = `-- name: UpdateHunterXP :exec
UPDATE hunter_profile SET
    xp = ?,
    level = ?,
    xp_to_next = ?,
    rank = ?,
    title = ?
WHERE id = 1
`

type UpdateHunterXPParams struct {
	Xp       sql.NullInt64  `json:"xp"`
	Level    sql.NullInt64  `json:"level"`
	XpToNext sql.NullInt64  `json:"xp_to_next"`
	Rank     sql.NullString `json:"rank"`
	Title    sql.NullString `json:"title"`
}

func (q *Queries) UpdateHunterXP(ctx context.Context, arg UpdateHunterXPParams) error {
	_, err := q.db.ExecContext(ctx, updateHunterXP,
		arg.Xp,
		arg.Level,
		arg.XpToNext,
		arg.Rank,
		arg.Title,
	)
	return err
}

const updateQuestProgress = `-- name: UpdateQuestProgress :exec
UPDATE daily_quests SET progress = ?, completed = ? WHERE id = ?
`

type UpdateQuestProgressParams struct {
	Progress  sql.NullInt64 `json:"progress"`
	Completed sql.NullInt64 `json:"completed"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateQuestProgress(ctx context.Context, arg UpdateQuestProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestProgress, arg.Progress, arg.Completed, arg.ID)
	return err
}

const updateStreak = `-- name: UpdateStreak :exec
UPDATE hunter_profile SET
    streak_current = ?,
    streak_best = ?,
    last_active_date = ?
WHERE id = 1
`

type UpdateStreakParams struct {
	StreakCurrent  sql.NullInt64  `json:"streak_current"`
	StreakBest     sql.NullInt64  `json:"streak_best"`
	LastActiveDate sql.NullString `json:"last_active_date"`
}

func (q *Queries) UpdateStreak(ctx context.Context, arg UpdateStreakParams) error {
	_, err := q.db.ExecContext(ctx, updateStreak, arg.StreakCurrent, arg.StreakBest, arg.LastActiveDate)
	return err
}

const upsertAchievement = `-- name: UpsertAchievement :exec
INSERT INTO achievements (id, name, description, icon, category, xp_reward, unlocked_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    description = excluded.description,
    icon = excluded.icon,
    category = excluded.category,
    xp_reward = excluded.xp_reward
`

type UpsertAchievementParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	Category    sql.NullString `json:"category"`
	XpReward    sql.NullInt64  `json:"xp_reward"`
	UnlockedAt  sql.NullInt64  `json:"unlocked_at"`
}

func (q *Queries) UpsertAchievement(ctx context.Context, arg UpsertAchievementParams) error {
	_, err := q.db.ExecContext(ctx, upsertAchievement,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Category,
		arg.XpReward,
		arg.UnlockedAt,
	)
	return err
}
