// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journal.sql

package db

import (
	"context"
	"database/sql"
)

const getDailyStats = `-- name: GetDailyStats :one
SELECT date, project_id, session_count, total_duration_secs, total_cost_micros, total_input_tokens, total_output_tokens, total_tool_calls, total_commits, pr_count, top_files FROM daily_stats WHERE date = ? AND project_id = ?
`

type GetDailyStatsParams struct {
	Date      string `json:"date"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetDailyStats(ctx context.Context, arg GetDailyStatsParams) (DailyStat, error) {
	row := q.db.QueryRowContext(ctx, getDailyStats, arg.Date, arg.ProjectID)
	var i DailyStat
	err := row.Scan(
		&i.Date,
		&i.ProjectID,
		&i.SessionCount,
		&i.TotalDurationSecs,
		&i.TotalCostMicros,
		&i.TotalInputTokens,
		&i.TotalOutputTokens,
		&i.TotalToolCalls,
		&i.TotalCommits,
		&i.PrCount,
		&i.TopFiles,
	)
	return i, err
}

const getLastActiveSession = `-- name: GetLastActiveSession :one
SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct, date, summary, outcome, files_touched, git_commits, git_lines_added, git_lines_removed, branch, pr_url, pr_status, provider, session_goal, session_type, tool_summary, keywords, parent_session_id FROM sessions WHERE status IN ('active', 'completed') ORDER BY started_at DESC LIMIT 1
`

func (q *Queries) GetLastActiveSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRowContext(ctx, getLastActiveSession)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Cwd,
		&i.Repo,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.Entrypoint,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TaskCount,
		&i.CompletedTasks,
		&i.XpEarned,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.EstimatedCostMicros,
		&i.MessageCount,
		&i.ToolUseCount,
		&i.FirstPrompt,
		&i.ToolBreakdown,
		&i.LastInputTokens,
		&i.ContextUsedPct,
		&i.Date,
		&i.Summary,
		&i.Outcome,
		&i.FilesTouched,
		&i.GitCommits,
		&i.GitLinesAdded,
		&i.GitLinesRemoved,
		&i.Branch,
		&i.PrUrl,
		&i.PrStatus,
		&i.Provider,
		&i.SessionGoal,
		&i.SessionType,
		&i.ToolSummary,
		&i.Keywords,
		&i.ParentSessionID,
	)
	return i, err
}

const getSessionJournal = `-- name: GetSessionJournal :one

SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct, date, summary, outcome, files_touched, git_commits, git_lines_added, git_lines_removed, branch, pr_url, pr_status, provider, session_goal, session_type, tool_summary, keywords, parent_session_id FROM sessions WHERE id = ?
`

// journal.sql - Activity Journal queries for sessions and daily stats
// Author: Subash Karki
func (q *Queries) GetSessionJournal(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionJournal, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Cwd,
		&i.Repo,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.Entrypoint,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TaskCount,
		&i.CompletedTasks,
		&i.XpEarned,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.EstimatedCostMicros,
		&i.MessageCount,
		&i.ToolUseCount,
		&i.FirstPrompt,
		&i.ToolBreakdown,
		&i.LastInputTokens,
		&i.ContextUsedPct,
		&i.Date,
		&i.Summary,
		&i.Outcome,
		&i.FilesTouched,
		&i.GitCommits,
		&i.GitLinesAdded,
		&i.GitLinesRemoved,
		&i.Branch,
		&i.PrUrl,
		&i.PrStatus,
		&i.Provider,
		&i.SessionGoal,
		&i.SessionType,
		&i.ToolSummary,
		&i.Keywords,
		&i.ParentSessionID,
	)
	return i, err
}

const listDailyStatsRange = `-- name: ListDailyStatsRange :many
SELECT date, project_id, session_count, total_duration_secs, total_cost_micros, total_input_tokens, total_output_tokens, total_tool_calls, total_commits, pr_count, top_files FROM daily_stats WHERE date BETWEEN ? AND ? AND project_id = '__global__' ORDER BY date
`

type ListDailyStatsRangeParams struct {
	Date   string `json:"date"`
	Date_2 string `json:"date_2"`
}

func (q *Queries) ListDailyStatsRange(ctx context.Context, arg ListDailyStatsRangeParams) ([]DailyStat, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStatsRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStat{}
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.Date,
			&i.ProjectID,
			&i.SessionCount,
			&i.TotalDurationSecs,
			&i.TotalCostMicros,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalToolCalls,
			&i.TotalCommits,
			&i.PrCount,
			&i.TopFiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyStatsRangeByProject = `-- name: ListDailyStatsRangeByProject :many
SELECT date, project_id, session_count, total_duration_secs, total_cost_micros, total_input_tokens, total_output_tokens, total_tool_calls, total_commits, pr_count, top_files FROM daily_stats WHERE date BETWEEN ? AND ? AND project_id = ? ORDER BY date
`

type ListDailyStatsRangeByProjectParams struct {
	Date      string `json:"date"`
	Date_2    string `json:"date_2"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListDailyStatsRangeByProject(ctx context.Context, arg ListDailyStatsRangeByProjectParams) ([]DailyStat, error) {
	rows, err := q.db.QueryContext(ctx, listDailyStatsRangeByProject, arg.Date, arg.Date_2, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStat{}
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.Date,
			&i.ProjectID,
			&i.SessionCount,
			&i.TotalDurationSecs,
			&i.TotalCostMicros,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.TotalToolCalls,
			&i.TotalCommits,
			&i.PrCount,
			&i.TopFiles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSessions = `-- name: ListRecentSessions :many
SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct, date, summary, outcome, files_touched, git_commits, git_lines_added, git_lines_removed, branch, pr_url, pr_status, provider, session_goal, session_type, tool_summary, keywords, parent_session_id FROM sessions WHERE status IN ('completed', 'active') ORDER BY started_at DESC LIMIT ?
`

func (q *Queries) ListRecentSessions(ctx context.Context, limit int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Cwd,
			&i.Repo,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.Entrypoint,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TaskCount,
			&i.CompletedTasks,
			&i.XpEarned,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.EstimatedCostMicros,
			&i.MessageCount,
			&i.ToolUseCount,
			&i.FirstPrompt,
			&i.ToolBreakdown,
			&i.LastInputTokens,
			&i.ContextUsedPct,
			&i.Date,
			&i.Summary,
			&i.Outcome,
			&i.FilesTouched,
			&i.GitCommits,
			&i.GitLinesAdded,
			&i.GitLinesRemoved,
			&i.Branch,
			&i.PrUrl,
			&i.PrStatus,
			&i.Provider,
			&i.SessionGoal,
			&i.SessionType,
			&i.ToolSummary,
			&i.Keywords,
			&i.ParentSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByDate = `-- name: ListSessionsByDate :many
SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct, date, summary, outcome, files_touched, git_commits, git_lines_added, git_lines_removed, branch, pr_url, pr_status, provider, session_goal, session_type, tool_summary, keywords, parent_session_id FROM sessions WHERE date = ? ORDER BY started_at DESC
`

func (q *Queries) ListSessionsByDate(ctx context.Context, date sql.NullString) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Cwd,
			&i.Repo,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.Entrypoint,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TaskCount,
			&i.CompletedTasks,
			&i.XpEarned,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.EstimatedCostMicros,
			&i.MessageCount,
			&i.ToolUseCount,
			&i.FirstPrompt,
			&i.ToolBreakdown,
			&i.LastInputTokens,
			&i.ContextUsedPct,
			&i.Date,
			&i.Summary,
			&i.Outcome,
			&i.FilesTouched,
			&i.GitCommits,
			&i.GitLinesAdded,
			&i.GitLinesRemoved,
			&i.Branch,
			&i.PrUrl,
			&i.PrStatus,
			&i.Provider,
			&i.SessionGoal,
			&i.SessionType,
			&i.ToolSummary,
			&i.Keywords,
			&i.ParentSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByProject = `-- name: ListSessionsByProject :many
SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct, date, summary, outcome, files_touched, git_commits, git_lines_added, git_lines_removed, branch, pr_url, pr_status, provider, session_goal, session_type, tool_summary, keywords, parent_session_id FROM sessions WHERE repo = ? ORDER BY started_at DESC LIMIT ?
`

type ListSessionsByProjectParams struct {
	Repo  sql.NullString `json:"repo"`
	Limit int64          `json:"limit"`
}

func (q *Queries) ListSessionsByProject(ctx context.Context, arg ListSessionsByProjectParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByProject, arg.Repo, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Cwd,
			&i.Repo,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.Entrypoint,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TaskCount,
			&i.CompletedTasks,
			&i.XpEarned,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.EstimatedCostMicros,
			&i.MessageCount,
			&i.ToolUseCount,
			&i.FirstPrompt,
			&i.ToolBreakdown,
			&i.LastInputTokens,
			&i.ContextUsedPct,
			&i.Date,
			&i.Summary,
			&i.Outcome,
			&i.FilesTouched,
			&i.GitCommits,
			&i.GitLinesAdded,
			&i.GitLinesRemoved,
			&i.Branch,
			&i.PrUrl,
			&i.PrStatus,
			&i.Provider,
			&i.SessionGoal,
			&i.SessionType,
			&i.ToolSummary,
			&i.Keywords,
			&i.ParentSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionJournal = `-- name: UpdateSessionJournal :exec
UPDATE sessions SET
    date = ?,
    summary = ?,
    outcome = ?,
    files_touched = ?,
    git_commits = ?,
    git_lines_added = ?,
    git_lines_removed = ?,
    branch = ?,
    pr_url = ?,
    pr_status = ?
WHERE id = ?
`

type UpdateSessionJournalParams struct {
	Date            sql.NullString `json:"date"`
	Summary         sql.NullString `json:"summary"`
	Outcome         sql.NullString `json:"outcome"`
	FilesTouched    sql.NullString `json:"files_touched"`
	GitCommits      sql.NullInt64  `json:"git_commits"`
	GitLinesAdded   sql.NullInt64  `json:"git_lines_added"`
	GitLinesRemoved sql.NullInt64  `json:"git_lines_removed"`
	Branch          sql.NullString `json:"branch"`
	PrUrl           sql.NullString `json:"pr_url"`
	PrStatus        sql.NullString `json:"pr_status"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateSessionJournal(ctx context.Context, arg UpdateSessionJournalParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionJournal,
		arg.Date,
		arg.Summary,
		arg.Outcome,
		arg.FilesTouched,
		arg.GitCommits,
		arg.GitLinesAdded,
		arg.GitLinesRemoved,
		arg.Branch,
		arg.PrUrl,
		arg.PrStatus,
		arg.ID,
	)
	return err
}

const upsertDailyStats = `-- name: UpsertDailyStats :exec
INSERT INTO daily_stats (date, project_id, session_count, total_duration_secs, total_cost_micros, total_input_tokens, total_output_tokens, total_tool_calls, total_commits, pr_count, top_files)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (date, project_id)
DO UPDATE SET
    session_count = excluded.session_count,
    total_duration_secs = excluded.total_duration_secs,
    total_cost_micros = excluded.total_cost_micros,
    total_input_tokens = excluded.total_input_tokens,
    total_output_tokens = excluded.total_output_tokens,
    total_tool_calls = excluded.total_tool_calls,
    total_commits = excluded.total_commits,
    pr_count = excluded.pr_count,
    top_files = excluded.top_files
`

type UpsertDailyStatsParams struct {
	Date              string         `json:"date"`
	ProjectID         string         `json:"project_id"`
	SessionCount      sql.NullInt64  `json:"session_count"`
	TotalDurationSecs sql.NullInt64  `json:"total_duration_secs"`
	TotalCostMicros   sql.NullInt64  `json:"total_cost_micros"`
	TotalInputTokens  sql.NullInt64  `json:"total_input_tokens"`
	TotalOutputTokens sql.NullInt64  `json:"total_output_tokens"`
	TotalToolCalls    sql.NullInt64  `json:"total_tool_calls"`
	TotalCommits      sql.NullInt64  `json:"total_commits"`
	PrCount           sql.NullInt64  `json:"pr_count"`
	TopFiles          sql.NullString `json:"top_files"`
}

func (q *Queries) UpsertDailyStats(ctx context.Context, arg UpsertDailyStatsParams) error {
	_, err := q.db.ExecContext(ctx, upsertDailyStats,
		arg.Date,
		arg.ProjectID,
		arg.SessionCount,
		arg.TotalDurationSecs,
		arg.TotalCostMicros,
		arg.TotalInputTokens,
		arg.TotalOutputTokens,
		arg.TotalToolCalls,
		arg.TotalCommits,
		arg.PrCount,
		arg.TopFiles,
	)
	return err
}
