// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Achievement struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Icon        sql.NullString `json:"icon"`
	Category    sql.NullString `json:"category"`
	XpReward    sql.NullInt64  `json:"xp_reward"`
	UnlockedAt  sql.NullInt64  `json:"unlocked_at"`
}

type ActivityLog struct {
	ID        int64          `json:"id"`
	Timestamp int64          `json:"timestamp"`
	Type      string         `json:"type"`
	SessionID sql.NullString `json:"session_id"`
	Metadata  sql.NullString `json:"metadata"`
	XpEarned  sql.NullInt64  `json:"xp_earned"`
	Provider  string         `json:"provider"`
}

type ChatConversation struct {
	ID          string         `json:"id"`
	WorkspaceID sql.NullString `json:"workspace_id"`
	Title       string         `json:"title"`
	Model       sql.NullString `json:"model"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type ChatMessage struct {
	ID             string         `json:"id"`
	ConversationID sql.NullString `json:"conversation_id"`
	WorkspaceID    sql.NullString `json:"workspace_id"`
	Role           string         `json:"role"`
	Content        string         `json:"content"`
	Model          sql.NullString `json:"model"`
	CreatedAt      int64          `json:"created_at"`
}

type CustomRecipe struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Label       string         `json:"label"`
	Command     string         `json:"command"`
	Icon        sql.NullString `json:"icon"`
	Category    sql.NullString `json:"category"`
	Description sql.NullString `json:"description"`
	Favorite    sql.NullInt64  `json:"favorite"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type DailyQuest struct {
	ID        string        `json:"id"`
	Date      string        `json:"date"`
	QuestType string        `json:"quest_type"`
	Label     string        `json:"label"`
	Target    int64         `json:"target"`
	Progress  sql.NullInt64 `json:"progress"`
	Completed sql.NullInt64 `json:"completed"`
	XpReward  sql.NullInt64 `json:"xp_reward"`
}

type DailyStat struct {
	Date              string         `json:"date"`
	ProjectID         string         `json:"project_id"`
	SessionCount      sql.NullInt64  `json:"session_count"`
	TotalDurationSecs sql.NullInt64  `json:"total_duration_secs"`
	TotalCostMicros   sql.NullInt64  `json:"total_cost_micros"`
	TotalInputTokens  sql.NullInt64  `json:"total_input_tokens"`
	TotalOutputTokens sql.NullInt64  `json:"total_output_tokens"`
	TotalToolCalls    sql.NullInt64  `json:"total_tool_calls"`
	TotalCommits      sql.NullInt64  `json:"total_commits"`
	PrCount           sql.NullInt64  `json:"pr_count"`
	TopFiles          sql.NullString `json:"top_files"`
}

type GraphEdge struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	SourceID  string         `json:"source_id"`
	TargetID  string         `json:"target_id"`
	Type      string         `json:"type"`
	Weight    sql.NullInt64  `json:"weight"`
	Metadata  sql.NullString `json:"metadata"`
	CreatedAt int64          `json:"created_at"`
	UpdatedAt int64          `json:"updated_at"`
}

type GraphMetum struct {
	ProjectID     string        `json:"project_id"`
	LastBuiltAt   sql.NullInt64 `json:"last_built_at"`
	LastUpdatedAt sql.NullInt64 `json:"last_updated_at"`
	FileCount     sql.NullInt64 `json:"file_count"`
	EdgeCount     sql.NullInt64 `json:"edge_count"`
	Layer2Count   sql.NullInt64 `json:"layer2_count"`
	Coverage      sql.NullInt64 `json:"coverage"`
}

type GraphNode struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Type        string         `json:"type"`
	Path        sql.NullString `json:"path"`
	Name        sql.NullString `json:"name"`
	ContentHash sql.NullString `json:"content_hash"`
	Metadata    sql.NullString `json:"metadata"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

type HunterProfile struct {
	ID             int64          `json:"id"`
	Name           sql.NullString `json:"name"`
	Level          sql.NullInt64  `json:"level"`
	Xp             sql.NullInt64  `json:"xp"`
	XpToNext       sql.NullInt64  `json:"xp_to_next"`
	Rank           sql.NullString `json:"rank"`
	Title          sql.NullString `json:"title"`
	TotalSessions  sql.NullInt64  `json:"total_sessions"`
	TotalTasks     sql.NullInt64  `json:"total_tasks"`
	TotalRepos     sql.NullInt64  `json:"total_repos"`
	StreakCurrent  sql.NullInt64  `json:"streak_current"`
	StreakBest     sql.NullInt64  `json:"streak_best"`
	LastActiveDate sql.NullString `json:"last_active_date"`
	CreatedAt      sql.NullInt64  `json:"created_at"`
}

type HunterStat struct {
	ID           int64         `json:"id"`
	Strength     sql.NullInt64 `json:"strength"`
	Intelligence sql.NullInt64 `json:"intelligence"`
	Agility      sql.NullInt64 `json:"agility"`
	Vitality     sql.NullInt64 `json:"vitality"`
	Perception   sql.NullInt64 `json:"perception"`
	Sense        sql.NullInt64 `json:"sense"`
}

type PaneState struct {
	WorktreeID string `json:"worktree_id"`
	State      string `json:"state"`
	UpdatedAt  int64  `json:"updated_at"`
}

type Project struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	RepoPath        string         `json:"repo_path"`
	DefaultBranch   sql.NullString `json:"default_branch"`
	WorktreeBaseDir sql.NullString `json:"worktree_base_dir"`
	Color           sql.NullString `json:"color"`
	Profile         sql.NullString `json:"profile"`
	Starred         sql.NullInt64  `json:"starred"`
	CreatedAt       int64          `json:"created_at"`
}

type RecipeFavorite struct {
	ProjectID string `json:"project_id"`
	RecipeID  string `json:"recipe_id"`
	CreatedAt int64  `json:"created_at"`
}

type Session struct {
	ID                  string         `json:"id"`
	Pid                 sql.NullInt64  `json:"pid"`
	Cwd                 sql.NullString `json:"cwd"`
	Repo                sql.NullString `json:"repo"`
	Name                sql.NullString `json:"name"`
	Kind                sql.NullString `json:"kind"`
	Model               sql.NullString `json:"model"`
	Entrypoint          sql.NullString `json:"entrypoint"`
	StartedAt           sql.NullInt64  `json:"started_at"`
	EndedAt             sql.NullInt64  `json:"ended_at"`
	Status              sql.NullString `json:"status"`
	TaskCount           sql.NullInt64  `json:"task_count"`
	CompletedTasks      sql.NullInt64  `json:"completed_tasks"`
	XpEarned            sql.NullInt64  `json:"xp_earned"`
	InputTokens         sql.NullInt64  `json:"input_tokens"`
	OutputTokens        sql.NullInt64  `json:"output_tokens"`
	CacheReadTokens     sql.NullInt64  `json:"cache_read_tokens"`
	CacheWriteTokens    sql.NullInt64  `json:"cache_write_tokens"`
	EstimatedCostMicros sql.NullInt64  `json:"estimated_cost_micros"`
	MessageCount        sql.NullInt64  `json:"message_count"`
	ToolUseCount        sql.NullInt64  `json:"tool_use_count"`
	FirstPrompt         sql.NullString `json:"first_prompt"`
	ToolBreakdown       sql.NullString `json:"tool_breakdown"`
	LastInputTokens     sql.NullInt64  `json:"last_input_tokens"`
	ContextUsedPct      sql.NullInt64  `json:"context_used_pct"`
	Date                sql.NullString `json:"date"`
	Summary             sql.NullString `json:"summary"`
	Outcome             sql.NullString `json:"outcome"`
	FilesTouched        sql.NullString `json:"files_touched"`
	GitCommits          sql.NullInt64  `json:"git_commits"`
	GitLinesAdded       sql.NullInt64  `json:"git_lines_added"`
	GitLinesRemoved     sql.NullInt64  `json:"git_lines_removed"`
	Branch              sql.NullString `json:"branch"`
	PrUrl               sql.NullString `json:"pr_url"`
	PrStatus            sql.NullString `json:"pr_status"`
	Provider            string         `json:"provider"`
}

type SessionEvent struct {
	ID        int64          `json:"id"`
	SessionID string         `json:"session_id"`
	Type      string         `json:"type"`
	Data      sql.NullString `json:"data"`
	Timestamp int64          `json:"timestamp"`
}

type SessionPolicy struct {
	SessionID string `json:"session_id"`
	Policy    string `json:"policy"`
	UpdatedAt int64  `json:"updated_at"`
}

type Task struct {
	ID          string         `json:"id"`
	SessionID   sql.NullString `json:"session_id"`
	TaskNum     sql.NullInt64  `json:"task_num"`
	Subject     sql.NullString `json:"subject"`
	Description sql.NullString `json:"description"`
	Crew        sql.NullString `json:"crew"`
	Status      sql.NullString `json:"status"`
	ActiveForm  sql.NullString `json:"active_form"`
	Blocks      sql.NullString `json:"blocks"`
	BlockedBy   sql.NullString `json:"blocked_by"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
}

type TerminalSession struct {
	PaneID       string         `json:"pane_id"`
	WorktreeID   sql.NullString `json:"worktree_id"`
	Shell        sql.NullString `json:"shell"`
	Cwd          sql.NullString `json:"cwd"`
	Env          sql.NullString `json:"env"`
	Cols         sql.NullInt64  `json:"cols"`
	Rows         sql.NullInt64  `json:"rows"`
	Scrollback   sql.NullString `json:"scrollback"`
	Status       sql.NullString `json:"status"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	LastActiveAt sql.NullInt64  `json:"last_active_at"`
	EndedAt      sql.NullInt64  `json:"ended_at"`
	SessionID    sql.NullString `json:"session_id"`
	ProjectID    sql.NullString `json:"project_id"`
}

type UserPreference struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

type Workspace struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	Type         string         `json:"type"`
	Name         string         `json:"name"`
	Branch       string         `json:"branch"`
	WorktreePath sql.NullString `json:"worktree_path"`
	PortBase     sql.NullInt64  `json:"port_base"`
	SectionID    sql.NullString `json:"section_id"`
	BaseBranch   sql.NullString `json:"base_branch"`
	TabOrder     sql.NullInt64  `json:"tab_order"`
	IsActive     sql.NullInt64  `json:"is_active"`
	TicketUrl    sql.NullString `json:"ticket_url"`
	CreatedAt    int64          `json:"created_at"`
}

type WorkspaceSection struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Name        string         `json:"name"`
	TabOrder    sql.NullInt64  `json:"tab_order"`
	IsCollapsed sql.NullInt64  `json:"is_collapsed"`
	Color       sql.NullString `json:"color"`
	CreatedAt   int64          `json:"created_at"`
}
