// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package db

import (
	"context"
)

const getPreference = `-- name: GetPreference :one

SELECT value FROM user_preferences WHERE key = ?
`

// preferences.sql - Operations for user_preferences table
// Author: Subash Karki
func (q *Queries) GetPreference(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPreference, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listPreferences = `-- name: ListPreferences :many
SELECT "key", value, updated_at FROM user_preferences ORDER BY key ASC
`

func (q *Queries) ListPreferences(ctx context.Context) ([]UserPreference, error) {
	rows, err := q.db.QueryContext(ctx, listPreferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPreference{}
	for rows.Next() {
		var i UserPreference
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPreference = `-- name: SetPreference :exec
INSERT INTO user_preferences (key, value, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = excluded.updated_at
`

type SetPreferenceParams struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) SetPreference(ctx context.Context, arg SetPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, setPreference, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}
