// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_notes.sql

package db

import (
	"context"
)

const countProjectNotes = `-- name: CountProjectNotes :one
SELECT COUNT(*) FROM project_notes WHERE project_id = ?
`

func (q *Queries) CountProjectNotes(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectNotes, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProjectNote = `-- name: CreateProjectNote :exec
INSERT INTO project_notes (id, project_id, type, title, body, pinned, position, pos_x, pos_y, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectNoteParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Pinned    int64  `json:"pinned"`
	Position  int64  `json:"position"`
	PosX      int64  `json:"pos_x"`
	PosY      int64  `json:"pos_y"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateProjectNote(ctx context.Context, arg CreateProjectNoteParams) error {
	_, err := q.db.ExecContext(ctx, createProjectNote,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Pinned,
		arg.Position,
		arg.PosX,
		arg.PosY,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProjectNote = `-- name: DeleteProjectNote :exec
DELETE FROM project_notes WHERE id = ?
`

func (q *Queries) DeleteProjectNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectNote, id)
	return err
}

const getProjectNote = `-- name: GetProjectNote :one
SELECT id, project_id, type, title, body, pinned, position, created_at, updated_at, pos_x, pos_y FROM project_notes WHERE id = ?
`

func (q *Queries) GetProjectNote(ctx context.Context, id string) (ProjectNote, error) {
	row := q.db.QueryRowContext(ctx, getProjectNote, id)
	var i ProjectNote
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PosX,
		&i.PosY,
	)
	return i, err
}

const listProjectNotes = `-- name: ListProjectNotes :many

SELECT id, project_id, type, title, body, pinned, position, created_at, updated_at, pos_x, pos_y FROM project_notes WHERE project_id = ? ORDER BY pinned DESC, position ASC, created_at DESC
`

// Author: Subash Karki
func (q *Queries) ListProjectNotes(ctx context.Context, projectID string) ([]ProjectNote, error) {
	rows, err := q.db.QueryContext(ctx, listProjectNotes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectNote{}
	for rows.Next() {
		var i ProjectNote
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Pinned,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PosX,
			&i.PosY,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotePosition = `-- name: UpdateNotePosition :exec
UPDATE project_notes SET pos_x = ?, pos_y = ?, updated_at = ? WHERE id = ?
`

type UpdateNotePositionParams struct {
	PosX      int64  `json:"pos_x"`
	PosY      int64  `json:"pos_y"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateNotePosition(ctx context.Context, arg UpdateNotePositionParams) error {
	_, err := q.db.ExecContext(ctx, updateNotePosition,
		arg.PosX,
		arg.PosY,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateProjectNote = `-- name: UpdateProjectNote :exec
UPDATE project_notes SET title = ?, body = ?, type = ?, pinned = ?, position = ?, pos_x = ?, pos_y = ?, updated_at = ? WHERE id = ?
`

type UpdateProjectNoteParams struct {
	Title     string `json:"title"`
	Body      string `json:"body"`
	Type      string `json:"type"`
	Pinned    int64  `json:"pinned"`
	Position  int64  `json:"position"`
	PosX      int64  `json:"pos_x"`
	PosY      int64  `json:"pos_y"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateProjectNote(ctx context.Context, arg UpdateProjectNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectNote,
		arg.Title,
		arg.Body,
		arg.Type,
		arg.Pinned,
		arg.Position,
		arg.PosX,
		arg.PosY,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
