// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
)

const countStarredProjects = `-- name: CountStarredProjects :one
SELECT COUNT(*) FROM projects WHERE starred = 1
`

func (q *Queries) CountStarredProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStarredProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (
    id, name, repo_path, default_branch, worktree_base_dir,
    color, profile, starred, created_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type CreateProjectParams struct {
	ID              string         `json:"id"`
	Name            string         `json:"name"`
	RepoPath        string         `json:"repo_path"`
	DefaultBranch   sql.NullString `json:"default_branch"`
	WorktreeBaseDir sql.NullString `json:"worktree_base_dir"`
	Color           sql.NullString `json:"color"`
	Profile         sql.NullString `json:"profile"`
	Starred         sql.NullInt64  `json:"starred"`
	CreatedAt       int64          `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.RepoPath,
		arg.DefaultBranch,
		arg.WorktreeBaseDir,
		arg.Color,
		arg.Profile,
		arg.Starred,
		arg.CreatedAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const findProjectByRepoPath = `-- name: FindProjectByRepoPath :one
SELECT id, name, repo_path, default_branch, worktree_base_dir, color, profile, starred, created_at FROM projects WHERE repo_path = ?
`

func (q *Queries) FindProjectByRepoPath(ctx context.Context, repoPath string) (Project, error) {
	row := q.db.QueryRowContext(ctx, findProjectByRepoPath, repoPath)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoPath,
		&i.DefaultBranch,
		&i.WorktreeBaseDir,
		&i.Color,
		&i.Profile,
		&i.Starred,
		&i.CreatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one

SELECT id, name, repo_path, default_branch, worktree_base_dir, color, profile, starred, created_at FROM projects WHERE id = ?
`

// projects.sql - CRUD operations for projects table
// Author: Subash Karki
func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RepoPath,
		&i.DefaultBranch,
		&i.WorktreeBaseDir,
		&i.Color,
		&i.Profile,
		&i.Starred,
		&i.CreatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, repo_path, default_branch, worktree_base_dir, color, profile, starred, created_at FROM projects ORDER BY starred DESC, name ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepoPath,
			&i.DefaultBranch,
			&i.WorktreeBaseDir,
			&i.Color,
			&i.Profile,
			&i.Starred,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleStarProject = `-- name: ToggleStarProject :exec
UPDATE projects SET starred = CASE WHEN starred = 1 THEN 0 ELSE 1 END WHERE id = ?
`

func (q *Queries) ToggleStarProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, toggleStarProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET
    name = ?,
    repo_path = ?,
    default_branch = ?,
    worktree_base_dir = ?,
    color = ?,
    profile = ?,
    starred = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Name            string         `json:"name"`
	RepoPath        string         `json:"repo_path"`
	DefaultBranch   sql.NullString `json:"default_branch"`
	WorktreeBaseDir sql.NullString `json:"worktree_base_dir"`
	Color           sql.NullString `json:"color"`
	Profile         sql.NullString `json:"profile"`
	Starred         sql.NullInt64  `json:"starred"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.RepoPath,
		arg.DefaultBranch,
		arg.WorktreeBaseDir,
		arg.Color,
		arg.Profile,
		arg.Starred,
		arg.ID,
	)
	return err
}
