// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package db

import (
	"context"
	"database/sql"
)

const addRecipeFavorite = `-- name: AddRecipeFavorite :exec
INSERT OR IGNORE INTO recipe_favorites (project_id, recipe_id, created_at)
VALUES (?, ?, ?)
`

type AddRecipeFavoriteParams struct {
	ProjectID string `json:"project_id"`
	RecipeID  string `json:"recipe_id"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) AddRecipeFavorite(ctx context.Context, arg AddRecipeFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addRecipeFavorite, arg.ProjectID, arg.RecipeID, arg.CreatedAt)
	return err
}

const createCustomRecipe = `-- name: CreateCustomRecipe :exec
INSERT INTO custom_recipes (
    id, project_id, label, command, icon, category,
    description, favorite, created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type CreateCustomRecipeParams struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Label       string         `json:"label"`
	Command     string         `json:"command"`
	Icon        sql.NullString `json:"icon"`
	Category    sql.NullString `json:"category"`
	Description sql.NullString `json:"description"`
	Favorite    sql.NullInt64  `json:"favorite"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
}

func (q *Queries) CreateCustomRecipe(ctx context.Context, arg CreateCustomRecipeParams) error {
	_, err := q.db.ExecContext(ctx, createCustomRecipe,
		arg.ID,
		arg.ProjectID,
		arg.Label,
		arg.Command,
		arg.Icon,
		arg.Category,
		arg.Description,
		arg.Favorite,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCustomRecipe = `-- name: DeleteCustomRecipe :exec
DELETE FROM custom_recipes WHERE id = ?
`

func (q *Queries) DeleteCustomRecipe(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomRecipe, id)
	return err
}

const deleteCustomRecipesByProject = `-- name: DeleteCustomRecipesByProject :exec
DELETE FROM custom_recipes WHERE project_id = ?
`

func (q *Queries) DeleteCustomRecipesByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomRecipesByProject, projectID)
	return err
}

const deleteRecipeFavoritesByProject = `-- name: DeleteRecipeFavoritesByProject :exec
DELETE FROM recipe_favorites WHERE project_id = ?
`

func (q *Queries) DeleteRecipeFavoritesByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipeFavoritesByProject, projectID)
	return err
}

const getCustomRecipe = `-- name: GetCustomRecipe :one
SELECT id, project_id, label, command, icon, category, description, favorite, created_at, updated_at FROM custom_recipes WHERE id = ?
`

func (q *Queries) GetCustomRecipe(ctx context.Context, id string) (CustomRecipe, error) {
	row := q.db.QueryRowContext(ctx, getCustomRecipe, id)
	var i CustomRecipe
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Label,
		&i.Command,
		&i.Icon,
		&i.Category,
		&i.Description,
		&i.Favorite,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomRecipesByProject = `-- name: ListCustomRecipesByProject :many

SELECT id, project_id, label, command, icon, category, description, favorite, created_at, updated_at FROM custom_recipes WHERE project_id = ? ORDER BY created_at ASC
`

// recipes.sql - CRUD operations for custom_recipes and recipe_favorites tables
// Author: Subash Karki
func (q *Queries) ListCustomRecipesByProject(ctx context.Context, projectID string) ([]CustomRecipe, error) {
	rows, err := q.db.QueryContext(ctx, listCustomRecipesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomRecipe{}
	for rows.Next() {
		var i CustomRecipe
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Label,
			&i.Command,
			&i.Icon,
			&i.Category,
			&i.Description,
			&i.Favorite,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeFavorites = `-- name: ListRecipeFavorites :many
SELECT project_id, recipe_id, created_at FROM recipe_favorites WHERE project_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListRecipeFavorites(ctx context.Context, projectID string) ([]RecipeFavorite, error) {
	rows, err := q.db.QueryContext(ctx, listRecipeFavorites, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecipeFavorite{}
	for rows.Next() {
		var i RecipeFavorite
		if err := rows.Scan(&i.ProjectID, &i.RecipeID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRecipeFavorite = `-- name: RemoveRecipeFavorite :exec
DELETE FROM recipe_favorites WHERE project_id = ? AND recipe_id = ?
`

type RemoveRecipeFavoriteParams struct {
	ProjectID string `json:"project_id"`
	RecipeID  string `json:"recipe_id"`
}

func (q *Queries) RemoveRecipeFavorite(ctx context.Context, arg RemoveRecipeFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeRecipeFavorite, arg.ProjectID, arg.RecipeID)
	return err
}

const updateCustomRecipe = `-- name: UpdateCustomRecipe :exec
UPDATE custom_recipes SET
    label = ?,
    command = ?,
    icon = ?,
    category = ?,
    description = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateCustomRecipeParams struct {
	Label       string         `json:"label"`
	Command     string         `json:"command"`
	Icon        sql.NullString `json:"icon"`
	Category    sql.NullString `json:"category"`
	Description sql.NullString `json:"description"`
	UpdatedAt   int64          `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateCustomRecipe(ctx context.Context, arg UpdateCustomRecipeParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomRecipe,
		arg.Label,
		arg.Command,
		arg.Icon,
		arg.Category,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
