// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, pid, cwd, repo, name, kind, model, entrypoint,
    started_at, ended_at, status, task_count, completed_tasks,
    xp_earned, input_tokens, output_tokens, cache_read_tokens,
    cache_write_tokens, estimated_cost_micros, message_count,
    tool_use_count, first_prompt, tool_breakdown,
    last_input_tokens, context_used_pct
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateSessionParams struct {
	ID                  string         `json:"id"`
	Pid                 sql.NullInt64  `json:"pid"`
	Cwd                 sql.NullString `json:"cwd"`
	Repo                sql.NullString `json:"repo"`
	Name                sql.NullString `json:"name"`
	Kind                sql.NullString `json:"kind"`
	Model               sql.NullString `json:"model"`
	Entrypoint          sql.NullString `json:"entrypoint"`
	StartedAt           sql.NullInt64  `json:"started_at"`
	EndedAt             sql.NullInt64  `json:"ended_at"`
	Status              sql.NullString `json:"status"`
	TaskCount           sql.NullInt64  `json:"task_count"`
	CompletedTasks      sql.NullInt64  `json:"completed_tasks"`
	XpEarned            sql.NullInt64  `json:"xp_earned"`
	InputTokens         sql.NullInt64  `json:"input_tokens"`
	OutputTokens        sql.NullInt64  `json:"output_tokens"`
	CacheReadTokens     sql.NullInt64  `json:"cache_read_tokens"`
	CacheWriteTokens    sql.NullInt64  `json:"cache_write_tokens"`
	EstimatedCostMicros sql.NullInt64  `json:"estimated_cost_micros"`
	MessageCount        sql.NullInt64  `json:"message_count"`
	ToolUseCount        sql.NullInt64  `json:"tool_use_count"`
	FirstPrompt         sql.NullString `json:"first_prompt"`
	ToolBreakdown       sql.NullString `json:"tool_breakdown"`
	LastInputTokens     sql.NullInt64  `json:"last_input_tokens"`
	ContextUsedPct      sql.NullInt64  `json:"context_used_pct"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Pid,
		arg.Cwd,
		arg.Repo,
		arg.Name,
		arg.Kind,
		arg.Model,
		arg.Entrypoint,
		arg.StartedAt,
		arg.EndedAt,
		arg.Status,
		arg.TaskCount,
		arg.CompletedTasks,
		arg.XpEarned,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.EstimatedCostMicros,
		arg.MessageCount,
		arg.ToolUseCount,
		arg.FirstPrompt,
		arg.ToolBreakdown,
		arg.LastInputTokens,
		arg.ContextUsedPct,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one

SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct FROM sessions WHERE id = ?
`

// sessions.sql - CRUD operations for sessions table
// Author: Subash Karki
func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Cwd,
		&i.Repo,
		&i.Name,
		&i.Kind,
		&i.Model,
		&i.Entrypoint,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.TaskCount,
		&i.CompletedTasks,
		&i.XpEarned,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.EstimatedCostMicros,
		&i.MessageCount,
		&i.ToolUseCount,
		&i.FirstPrompt,
		&i.ToolBreakdown,
		&i.LastInputTokens,
		&i.ContextUsedPct,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct FROM sessions WHERE status = 'active' ORDER BY started_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Cwd,
			&i.Repo,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.Entrypoint,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TaskCount,
			&i.CompletedTasks,
			&i.XpEarned,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.EstimatedCostMicros,
			&i.MessageCount,
			&i.ToolUseCount,
			&i.FirstPrompt,
			&i.ToolBreakdown,
			&i.LastInputTokens,
			&i.ContextUsedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct FROM sessions ORDER BY started_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Cwd,
			&i.Repo,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.Entrypoint,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TaskCount,
			&i.CompletedTasks,
			&i.XpEarned,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.EstimatedCostMicros,
			&i.MessageCount,
			&i.ToolUseCount,
			&i.FirstPrompt,
			&i.ToolBreakdown,
			&i.LastInputTokens,
			&i.ContextUsedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByStatus = `-- name: ListSessionsByStatus :many
SELECT id, pid, cwd, repo, name, kind, model, entrypoint, started_at, ended_at, status, task_count, completed_tasks, xp_earned, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, estimated_cost_micros, message_count, tool_use_count, first_prompt, tool_breakdown, last_input_tokens, context_used_pct FROM sessions WHERE status = ? ORDER BY started_at DESC
`

func (q *Queries) ListSessionsByStatus(ctx context.Context, status sql.NullString) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Cwd,
			&i.Repo,
			&i.Name,
			&i.Kind,
			&i.Model,
			&i.Entrypoint,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.TaskCount,
			&i.CompletedTasks,
			&i.XpEarned,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.EstimatedCostMicros,
			&i.MessageCount,
			&i.ToolUseCount,
			&i.FirstPrompt,
			&i.ToolBreakdown,
			&i.LastInputTokens,
			&i.ContextUsedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions SET
    pid = ?,
    cwd = ?,
    repo = ?,
    name = ?,
    kind = ?,
    model = ?,
    entrypoint = ?,
    ended_at = ?,
    status = ?,
    task_count = ?,
    completed_tasks = ?,
    xp_earned = ?,
    input_tokens = ?,
    output_tokens = ?,
    cache_read_tokens = ?,
    cache_write_tokens = ?,
    estimated_cost_micros = ?,
    message_count = ?,
    tool_use_count = ?,
    first_prompt = ?,
    tool_breakdown = ?,
    last_input_tokens = ?,
    context_used_pct = ?
WHERE id = ?
`

type UpdateSessionParams struct {
	Pid                 sql.NullInt64  `json:"pid"`
	Cwd                 sql.NullString `json:"cwd"`
	Repo                sql.NullString `json:"repo"`
	Name                sql.NullString `json:"name"`
	Kind                sql.NullString `json:"kind"`
	Model               sql.NullString `json:"model"`
	Entrypoint          sql.NullString `json:"entrypoint"`
	EndedAt             sql.NullInt64  `json:"ended_at"`
	Status              sql.NullString `json:"status"`
	TaskCount           sql.NullInt64  `json:"task_count"`
	CompletedTasks      sql.NullInt64  `json:"completed_tasks"`
	XpEarned            sql.NullInt64  `json:"xp_earned"`
	InputTokens         sql.NullInt64  `json:"input_tokens"`
	OutputTokens        sql.NullInt64  `json:"output_tokens"`
	CacheReadTokens     sql.NullInt64  `json:"cache_read_tokens"`
	CacheWriteTokens    sql.NullInt64  `json:"cache_write_tokens"`
	EstimatedCostMicros sql.NullInt64  `json:"estimated_cost_micros"`
	MessageCount        sql.NullInt64  `json:"message_count"`
	ToolUseCount        sql.NullInt64  `json:"tool_use_count"`
	FirstPrompt         sql.NullString `json:"first_prompt"`
	ToolBreakdown       sql.NullString `json:"tool_breakdown"`
	LastInputTokens     sql.NullInt64  `json:"last_input_tokens"`
	ContextUsedPct      sql.NullInt64  `json:"context_used_pct"`
	ID                  string         `json:"id"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.Pid,
		arg.Cwd,
		arg.Repo,
		arg.Name,
		arg.Kind,
		arg.Model,
		arg.Entrypoint,
		arg.EndedAt,
		arg.Status,
		arg.TaskCount,
		arg.CompletedTasks,
		arg.XpEarned,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.EstimatedCostMicros,
		arg.MessageCount,
		arg.ToolUseCount,
		arg.FirstPrompt,
		arg.ToolBreakdown,
		arg.LastInputTokens,
		arg.ContextUsedPct,
		arg.ID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET
    status = ?,
    ended_at = ?
WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status  sql.NullString `json:"status"`
	EndedAt sql.NullInt64  `json:"ended_at"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.EndedAt, arg.ID)
	return err
}

const updateSessionEnrichment = `-- name: UpdateSessionEnrichment :exec
UPDATE sessions SET
    model = ?,
    input_tokens = ?,
    output_tokens = ?,
    cache_read_tokens = ?,
    cache_write_tokens = ?,
    estimated_cost_micros = ?,
    message_count = ?,
    tool_use_count = ?,
    first_prompt = ?,
    tool_breakdown = ?,
    last_input_tokens = ?
WHERE id = ?
`

type UpdateSessionEnrichmentParams struct {
	Model               sql.NullString `json:"model"`
	InputTokens         sql.NullInt64  `json:"input_tokens"`
	OutputTokens        sql.NullInt64  `json:"output_tokens"`
	CacheReadTokens     sql.NullInt64  `json:"cache_read_tokens"`
	CacheWriteTokens    sql.NullInt64  `json:"cache_write_tokens"`
	EstimatedCostMicros sql.NullInt64  `json:"estimated_cost_micros"`
	MessageCount        sql.NullInt64  `json:"message_count"`
	ToolUseCount        sql.NullInt64  `json:"tool_use_count"`
	FirstPrompt         sql.NullString `json:"first_prompt"`
	ToolBreakdown       sql.NullString `json:"tool_breakdown"`
	LastInputTokens     sql.NullInt64  `json:"last_input_tokens"`
	ID                  string         `json:"id"`
}

// UpdateSessionEnrichment updates only scanner-derived enrichment fields.
// It deliberately omits status and ended_at to avoid the read-modify-write
// race with session_watcher, which exclusively owns those columns.
func (q *Queries) UpdateSessionEnrichment(ctx context.Context, arg UpdateSessionEnrichmentParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionEnrichment,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.EstimatedCostMicros,
		arg.MessageCount,
		arg.ToolUseCount,
		arg.FirstPrompt,
		arg.ToolBreakdown,
		arg.LastInputTokens,
		arg.ID,
	)
	return err
}

const updateSessionTokens = `-- name: UpdateSessionTokens :exec
UPDATE sessions SET
    input_tokens = ?,
    output_tokens = ?,
    cache_read_tokens = ?,
    cache_write_tokens = ?,
    estimated_cost_micros = ?,
    message_count = ?,
    tool_use_count = ?,
    last_input_tokens = ?,
    context_used_pct = ?
WHERE id = ?
`

type UpdateSessionTokensParams struct {
	InputTokens         sql.NullInt64 `json:"input_tokens"`
	OutputTokens        sql.NullInt64 `json:"output_tokens"`
	CacheReadTokens     sql.NullInt64 `json:"cache_read_tokens"`
	CacheWriteTokens    sql.NullInt64 `json:"cache_write_tokens"`
	EstimatedCostMicros sql.NullInt64 `json:"estimated_cost_micros"`
	MessageCount        sql.NullInt64 `json:"message_count"`
	ToolUseCount        sql.NullInt64 `json:"tool_use_count"`
	LastInputTokens     sql.NullInt64 `json:"last_input_tokens"`
	ContextUsedPct      sql.NullInt64 `json:"context_used_pct"`
	ID                  string        `json:"id"`
}

func (q *Queries) UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTokens,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.EstimatedCostMicros,
		arg.MessageCount,
		arg.ToolUseCount,
		arg.LastInputTokens,
		arg.ContextUsedPct,
		arg.ID,
	)
	return err
}
