// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
    id, session_id, task_num, subject, description, crew,
    status, active_form, blocks, blocked_by,
    created_at, updated_at, duration_ms
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
`

type CreateTaskParams struct {
	ID          string         `json:"id"`
	SessionID   sql.NullString `json:"session_id"`
	TaskNum     sql.NullInt64  `json:"task_num"`
	Subject     sql.NullString `json:"subject"`
	Description sql.NullString `json:"description"`
	Crew        sql.NullString `json:"crew"`
	Status      sql.NullString `json:"status"`
	ActiveForm  sql.NullString `json:"active_form"`
	Blocks      sql.NullString `json:"blocks"`
	BlockedBy   sql.NullString `json:"blocked_by"`
	CreatedAt   sql.NullInt64  `json:"created_at"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.SessionID,
		arg.TaskNum,
		arg.Subject,
		arg.Description,
		arg.Crew,
		arg.Status,
		arg.ActiveForm,
		arg.Blocks,
		arg.BlockedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DurationMs,
	)
	return err
}

const getTask = `-- name: GetTask :one

SELECT id, session_id, task_num, subject, description, crew, status, active_form, blocks, blocked_by, created_at, updated_at, duration_ms FROM tasks WHERE id = ?
`

// tasks.sql - CRUD operations for tasks table
// Author: Subash Karki
func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TaskNum,
		&i.Subject,
		&i.Description,
		&i.Crew,
		&i.Status,
		&i.ActiveForm,
		&i.Blocks,
		&i.BlockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DurationMs,
	)
	return i, err
}

const incrementSessionCompletedTasks = `-- name: IncrementSessionCompletedTasks :exec
UPDATE sessions SET completed_tasks = completed_tasks + 1 WHERE id = ?
`

func (q *Queries) IncrementSessionCompletedTasks(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementSessionCompletedTasks, id)
	return err
}

const incrementSessionTaskCount = `-- name: IncrementSessionTaskCount :exec
UPDATE sessions SET task_count = task_count + 1 WHERE id = ?
`

func (q *Queries) IncrementSessionTaskCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementSessionTaskCount, id)
	return err
}

const listTasksBySession = `-- name: ListTasksBySession :many
SELECT id, session_id, task_num, subject, description, crew, status, active_form, blocks, blocked_by, created_at, updated_at, duration_ms FROM tasks WHERE session_id = ? ORDER BY task_num ASC
`

func (q *Queries) ListTasksBySession(ctx context.Context, sessionID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TaskNum,
			&i.Subject,
			&i.Description,
			&i.Crew,
			&i.Status,
			&i.ActiveForm,
			&i.Blocks,
			&i.BlockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET
    subject = ?,
    description = ?,
    crew = ?,
    status = ?,
    active_form = ?,
    blocks = ?,
    blocked_by = ?,
    updated_at = ?,
    duration_ms = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	Subject     sql.NullString `json:"subject"`
	Description sql.NullString `json:"description"`
	Crew        sql.NullString `json:"crew"`
	Status      sql.NullString `json:"status"`
	ActiveForm  sql.NullString `json:"active_form"`
	Blocks      sql.NullString `json:"blocks"`
	BlockedBy   sql.NullString `json:"blocked_by"`
	UpdatedAt   sql.NullInt64  `json:"updated_at"`
	DurationMs  sql.NullInt64  `json:"duration_ms"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Subject,
		arg.Description,
		arg.Crew,
		arg.Status,
		arg.ActiveForm,
		arg.Blocks,
		arg.BlockedBy,
		arg.UpdatedAt,
		arg.DurationMs,
		arg.ID,
	)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET
    status = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status    sql.NullString `json:"status"`
	UpdatedAt sql.NullInt64  `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
