// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: terminal.sql

package db

import (
	"context"
	"database/sql"
)

const createTerminalSession = `-- name: CreateTerminalSession :exec
INSERT INTO terminal_sessions (
    pane_id, worktree_id, shell, cwd, env,
    cols, rows, scrollback, status,
    started_at, last_active_at, ended_at
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
`

type CreateTerminalSessionParams struct {
	PaneID       string         `json:"pane_id"`
	WorktreeID   sql.NullString `json:"worktree_id"`
	Shell        sql.NullString `json:"shell"`
	Cwd          sql.NullString `json:"cwd"`
	Env          sql.NullString `json:"env"`
	Cols         sql.NullInt64  `json:"cols"`
	Rows         sql.NullInt64  `json:"rows"`
	Scrollback   sql.NullString `json:"scrollback"`
	Status       sql.NullString `json:"status"`
	StartedAt    sql.NullInt64  `json:"started_at"`
	LastActiveAt sql.NullInt64  `json:"last_active_at"`
	EndedAt      sql.NullInt64  `json:"ended_at"`
}

func (q *Queries) CreateTerminalSession(ctx context.Context, arg CreateTerminalSessionParams) error {
	_, err := q.db.ExecContext(ctx, createTerminalSession,
		arg.PaneID,
		arg.WorktreeID,
		arg.Shell,
		arg.Cwd,
		arg.Env,
		arg.Cols,
		arg.Rows,
		arg.Scrollback,
		arg.Status,
		arg.StartedAt,
		arg.LastActiveAt,
		arg.EndedAt,
	)
	return err
}

const endTerminalSession = `-- name: EndTerminalSession :exec
UPDATE terminal_sessions SET
    status = 'ended',
    ended_at = ?
WHERE pane_id = ?
`

type EndTerminalSessionParams struct {
	EndedAt sql.NullInt64 `json:"ended_at"`
	PaneID  string        `json:"pane_id"`
}

func (q *Queries) EndTerminalSession(ctx context.Context, arg EndTerminalSessionParams) error {
	_, err := q.db.ExecContext(ctx, endTerminalSession, arg.EndedAt, arg.PaneID)
	return err
}

const getTerminalSession = `-- name: GetTerminalSession :one

SELECT pane_id, worktree_id, shell, cwd, env, cols, "rows", scrollback, status, started_at, last_active_at, ended_at FROM terminal_sessions WHERE pane_id = ?
`

// terminal.sql - CRUD operations for terminal_sessions table
// Author: Subash Karki
func (q *Queries) GetTerminalSession(ctx context.Context, paneID string) (TerminalSession, error) {
	row := q.db.QueryRowContext(ctx, getTerminalSession, paneID)
	var i TerminalSession
	err := row.Scan(
		&i.PaneID,
		&i.WorktreeID,
		&i.Shell,
		&i.Cwd,
		&i.Env,
		&i.Cols,
		&i.Rows,
		&i.Scrollback,
		&i.Status,
		&i.StartedAt,
		&i.LastActiveAt,
		&i.EndedAt,
	)
	return i, err
}

const listActiveTerminals = `-- name: ListActiveTerminals :many
SELECT pane_id, worktree_id, shell, cwd, env, cols, "rows", scrollback, status, started_at, last_active_at, ended_at FROM terminal_sessions WHERE status = 'active' ORDER BY started_at DESC
`

func (q *Queries) ListActiveTerminals(ctx context.Context) ([]TerminalSession, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTerminals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TerminalSession{}
	for rows.Next() {
		var i TerminalSession
		if err := rows.Scan(
			&i.PaneID,
			&i.WorktreeID,
			&i.Shell,
			&i.Cwd,
			&i.Env,
			&i.Cols,
			&i.Rows,
			&i.Scrollback,
			&i.Status,
			&i.StartedAt,
			&i.LastActiveAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTerminalLastActive = `-- name: UpdateTerminalLastActive :exec
UPDATE terminal_sessions SET last_active_at = ? WHERE pane_id = ?
`

type UpdateTerminalLastActiveParams struct {
	LastActiveAt sql.NullInt64 `json:"last_active_at"`
	PaneID       string        `json:"pane_id"`
}

func (q *Queries) UpdateTerminalLastActive(ctx context.Context, arg UpdateTerminalLastActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateTerminalLastActive, arg.LastActiveAt, arg.PaneID)
	return err
}

const updateTerminalScrollback = `-- name: UpdateTerminalScrollback :exec
UPDATE terminal_sessions SET
    scrollback = ?,
    last_active_at = ?
WHERE pane_id = ?
`

type UpdateTerminalScrollbackParams struct {
	Scrollback   sql.NullString `json:"scrollback"`
	LastActiveAt sql.NullInt64  `json:"last_active_at"`
	PaneID       string         `json:"pane_id"`
}

func (q *Queries) UpdateTerminalScrollback(ctx context.Context, arg UpdateTerminalScrollbackParams) error {
	_, err := q.db.ExecContext(ctx, updateTerminalScrollback, arg.Scrollback, arg.LastActiveAt, arg.PaneID)
	return err
}
