// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worktrees.sql

package db

import (
	"context"
	"database/sql"
)

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (
    id, project_id, type, name, branch, worktree_path,
    port_base, section_id, base_branch, tab_order,
    is_active, ticket_url, created_at
) VALUES (
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?
)
`

type CreateWorkspaceParams struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	Type         string         `json:"type"`
	Name         string         `json:"name"`
	Branch       string         `json:"branch"`
	WorktreePath sql.NullString `json:"worktree_path"`
	PortBase     sql.NullInt64  `json:"port_base"`
	SectionID    sql.NullString `json:"section_id"`
	BaseBranch   sql.NullString `json:"base_branch"`
	TabOrder     sql.NullInt64  `json:"tab_order"`
	IsActive     sql.NullInt64  `json:"is_active"`
	TicketUrl    sql.NullString `json:"ticket_url"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Name,
		arg.Branch,
		arg.WorktreePath,
		arg.PortBase,
		arg.SectionID,
		arg.BaseBranch,
		arg.TabOrder,
		arg.IsActive,
		arg.TicketUrl,
		arg.CreatedAt,
	)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one

SELECT id, project_id, type, name, branch, worktree_path, port_base, section_id, base_branch, tab_order, is_active, ticket_url, created_at FROM workspaces WHERE id = ?
`

// worktrees.sql - CRUD operations for workspaces table
// Author: Subash Karki
func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Name,
		&i.Branch,
		&i.WorktreePath,
		&i.PortBase,
		&i.SectionID,
		&i.BaseBranch,
		&i.TabOrder,
		&i.IsActive,
		&i.TicketUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkspacesByProject = `-- name: ListWorkspacesByProject :many
SELECT id, project_id, type, name, branch, worktree_path, port_base, section_id, base_branch, tab_order, is_active, ticket_url, created_at FROM workspaces WHERE project_id = ? ORDER BY tab_order ASC
`

func (q *Queries) ListWorkspacesByProject(ctx context.Context, projectID string) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Type,
			&i.Name,
			&i.Branch,
			&i.WorktreePath,
			&i.PortBase,
			&i.SectionID,
			&i.BaseBranch,
			&i.TabOrder,
			&i.IsActive,
			&i.TicketUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkspaceActive = `-- name: SetWorkspaceActive :exec
UPDATE workspaces SET is_active = ? WHERE id = ?
`

type SetWorkspaceActiveParams struct {
	IsActive sql.NullInt64 `json:"is_active"`
	ID       string        `json:"id"`
}

func (q *Queries) SetWorkspaceActive(ctx context.Context, arg SetWorkspaceActiveParams) error {
	_, err := q.db.ExecContext(ctx, setWorkspaceActive, arg.IsActive, arg.ID)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces SET
    type = ?,
    name = ?,
    branch = ?,
    worktree_path = ?,
    port_base = ?,
    section_id = ?,
    base_branch = ?,
    tab_order = ?,
    is_active = ?,
    ticket_url = ?
WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Type         string         `json:"type"`
	Name         string         `json:"name"`
	Branch       string         `json:"branch"`
	WorktreePath sql.NullString `json:"worktree_path"`
	PortBase     sql.NullInt64  `json:"port_base"`
	SectionID    sql.NullString `json:"section_id"`
	BaseBranch   sql.NullString `json:"base_branch"`
	TabOrder     sql.NullInt64  `json:"tab_order"`
	IsActive     sql.NullInt64  `json:"is_active"`
	TicketUrl    sql.NullString `json:"ticket_url"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace,
		arg.Type,
		arg.Name,
		arg.Branch,
		arg.WorktreePath,
		arg.PortBase,
		arg.SectionID,
		arg.BaseBranch,
		arg.TabOrder,
		arg.IsActive,
		arg.TicketUrl,
		arg.ID,
	)
	return err
}
