// Author: Subash Karki

const App = () => (window as any).go?.['app']?.App;

export async function createTerminal(
  id: string,
  worktreeId: string,
  projectId: string,
  cwd: string,
  cols: number,
  rows: number,
): Promise<void> {
  try {
    await App()?.CreateTerminal(id, worktreeId, projectId, cwd, cols, rows);
  } catch (error) {
    console.error('[terminal] createTerminal failed', { id, error });
  }
}

export async function writeTerminal(id: string, data: string): Promise<void> {
  try {
    await App()?.WriteTerminal(id, data);
  } catch (error) {
    console.error('[terminal] writeTerminal failed', { id, error });
  }
}

export async function resizeTerminal(id: string, cols: number, rows: number): Promise<void> {
  try {
    await App()?.ResizeTerminal(id, cols, rows);
  } catch {}
}

export async function destroyTerminal(id: string): Promise<void> {
  try {
    await App()?.DestroyTerminal(id);
  } catch {}
}

export async function restoreTerminal(paneId: string): Promise<void> {
  try {
    await App()?.RestoreTerminal(paneId);
  } catch (error) {
    console.error('[terminal] restoreTerminal failed', { paneId, error });
  }
}

export async function destroyTerminalsForWorktree(worktreeId: string): Promise<void> {
  try {
    await App()?.DestroyTerminalsForWorktree(worktreeId);
  } catch (error) {
    console.error('[terminal] destroyTerminalsForWorktree failed', { worktreeId, error });
  }
}

export async function listTerminalsForWorktree(worktreeId: string): Promise<unknown[]> {
  try {
    return (await App()?.ListTerminalsForWorktree(worktreeId)) ?? [];
  } catch {
    return [];
  }
}

export interface TerminalSnapshot {
  pane_id: string;
  worktree_id: string;
  shell: string;
  cwd: string;
  cols: number;
  rows: number;
  scrollback: string;
  last_active_at: number;
}

export async function getTerminalSnapshots(): Promise<TerminalSnapshot[]> {
  try {
    return (await App()?.GetTerminalSnapshots()) ?? [];
  } catch {
    return [];
  }
}

export async function getTerminalScrollback(id: string): Promise<string> {
  try {
    return (await App()?.GetTerminalScrollback(id)) ?? '';
  } catch {
    return '';
  }
}

/**
 * Persist a full xterm visual state snapshot for `paneId`. Generated by
 * `@xterm/addon-serialize`. Replayed on next restore via `terminal.write(state)`.
 */
export async function saveTerminalSnapshot(paneId: string, state: string): Promise<void> {
  try {
    await App()?.SaveTerminalSnapshot(paneId, state);
  } catch (error) {
    console.error('[terminal] saveTerminalSnapshot failed', { paneId, error });
  }
}

/**
 * Fetch the previously-saved xterm state for `paneId`. Returns empty string
 * if no snapshot exists. The caller writes the result into the xterm
 * instance with `terminal.write(state)` BEFORE attaching to the live PTY.
 */
export async function getTerminalSnapshot(paneId: string): Promise<string> {
  try {
    return (await App()?.GetTerminalSnapshot(paneId)) ?? '';
  } catch {
    return '';
  }
}

export async function subscribeTerminal(sessionId: string): Promise<void> {
  try {
    await App()?.SubscribeTerminal(sessionId);
  } catch {}
}

export async function unsubscribeTerminal(sessionId: string): Promise<void> {
  try {
    await App()?.UnsubscribeTerminal(sessionId);
  } catch {}
}

export interface TerminalInfo {
  id: string;
  cwd: string;
  cols: number;
  rows: number;
}

export async function listTerminals(): Promise<TerminalInfo[]> {
  try {
    return (await App()?.ListTerminals()) ?? [];
  } catch {
    return [];
  }
}

/**
 * Run a project recipe in a new terminal session.
 * @param projectId - The project to run the recipe in
 * @param recipeId  - The recipe to execute
 * @returns The new terminal session ID
 */
export async function runRecipe(projectId: string, recipeId: string): Promise<string> {
  try {
    return (await App()?.RunRecipe(projectId, recipeId)) ?? '';
  } catch {
    return '';
  }
}

/**
 * Launch a Bubbletea TUI program and return its session ID.
 * The session ID can be subscribed to via the existing terminal infrastructure
 * using `terminal:{sessionId}:data` events.
 * @param programType - The type of TUI program to launch (e.g. 'setup-wizard')
 * @param args        - Key/value arguments passed to the TUI program
 * @returns The new session ID, or empty string if the binding is not ready
 */
export async function runBubbleteaProgram(
  programType: string,
  args: Record<string, string>,
): Promise<string> {
  try {
    return (await App()?.RunBubbleteaProgram(programType, args)) ?? '';
  } catch (error) {
    console.error('[terminal] runBubbleteaProgram failed', { programType, error });
    return '';
  }
}

/**
 * Write a command to the terminal's PTY stdin followed by a newline,
 * causing the shell to execute it immediately.
 * @param sessionId - The terminal session ID
 * @param command   - The command string to execute (no trailing newline needed)
 */
export async function runTerminalCommand(sessionId: string, command: string): Promise<void> {
  try {
    await App()?.RunTerminalCommand(sessionId, command);
  } catch (error) {
    console.error('[terminal] runTerminalCommand failed', { sessionId, error });
  }
}

/**
 * Send keyboard input to an active Bubbletea TUI session.
 * @param sessionId - The TUI session ID returned by runBubbleteaProgram
 * @param data      - Raw input string from xterm.js onData
 */
export async function writeBubbleteaProgram(sessionId: string, data: string): Promise<void> {
  try {
    await App()?.WriteBubbleteaProgram(sessionId, data);
  } catch (error) {
    console.error('[terminal] writeBubbleteaProgram failed', { sessionId, error });
  }
}
